{
 "title": "ClickHouse-Cluster-Monitor",
 "description": "整体资源展示与资源明细图表：CPU、内存、磁盘、IO、网络等监控指标！",
 "tags": [
  "Node_exporter",
  "Prometheus",
  "ClickHouse",
  "Zookeeper",
  "Grafana"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "ck_instance",
    "query": {
     "query": "label_values(node_uname_info{job=\"ck_cluster_exporter\"}, instance)"
    }
   },
   {
    "name": "zk_instance",
    "query": {
     "query": "label_values(node_uname_info{job=\"zk_cluster_exporter\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "CK集群监控", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "资源总览",
   "type": "table-old",
   "description": "分区使用率、磁盘读取、磁盘写入、下载带宽、上传带宽，如果有多个网卡或者多个分区，是采集的使用率最高的网卡或者分区的数值。\n\nTCP_连接数：当前状态为 ESTABLISHED 或 CLOSE-WAIT 的 TCP 连接数\n\nTCP_TW：当前状态为TIME-WAIT的TCP连接数，即等待关闭的TCP连接数",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "node_uname_info{job=\"ck_cluster_exporter\"} - 0",
     "legendFormat": "主机名"
    },
    {
     "expr": "sum(time() - node_boot_time_seconds{job=\"ck_cluster_exporter\"})by(instance)",
     "legendFormat": "运行时间"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=\"ck_cluster_exporter\"} - 0",
     "legendFormat": "总内存"
    },
    {
     "expr": "count(node_cpu_seconds_total{job=\"ck_cluster_exporter\",mode='system'}) by (instance)",
     "legendFormat": "总核数"
    },
    {
     "expr": "node_load5{job=\"ck_cluster_exporter\"}",
     "legendFormat": "5分钟负载"
    },
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{job=\"ck_cluster_exporter\",mode=\"idle\"}[$__interval])) by (instance)) * 100",
     "legendFormat": "CPU使用率"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{job=\"ck_cluster_exporter\"} / (node_memory_MemTotal_bytes{job=\"ck_cluster_exporter\"})))* 100",
     "legendFormat": "内存使用率"
    },
    {
     "expr": "max((node_filesystem_size_bytes{job=\"ck_cluster_exporter\",fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{job=\"ck_cluster_exporter\",fstype=~\"ext.?|xfs\"}) *100/(node_filesystem_avail_bytes {job=\"ck_cluster_exporter\",fstype=~\"ext.?|xfs\"}+(node_filesystem_size_bytes{job=\"ck_cluster_exporter\",fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{job=\"ck_cluster_exporter\",fstype=~\"ext.?|xfs\"})))by(instance)",
     "legendFormat": "分区使用率"
    },
    {
     "expr": "max(rate(node_disk_read_bytes_total{job=\"ck_cluster_exporter\"}[$__interval])) by (instance)",
     "legendFormat": "最大读取"
    },
    {
     "expr": "max(rate(node_disk_written_bytes_total{job=\"ck_cluster_exporter\"}[$__interval])) by (instance)",
     "legendFormat": "最大写入"
    },
    {
     "expr": "node_netstat_Tcp_CurrEstab{job=\"ck_cluster_exporter\"} - 0",
     "legendFormat": "连接数"
    },
    {
     "expr": "node_sockstat_TCP_tw{job=\"ck_cluster_exporter\"} - 0",
     "legendFormat": "TIME_WAIT"
    },
    {
     "expr": "max(rate(node_network_receive_bytes_total{job=\"ck_cluster_exporter\"}[$__interval])*8) by (instance)",
     "legendFormat": "下载带宽"
    },
    {
     "expr": "max(rate(node_network_transmit_bytes_total{job=\"ck_cluster_exporter\"}[$__interval])*8) by (instance)",
     "legendFormat": "上传带宽"
    }
   ]
  },
  {
   "title": "CPU使用率",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{job=\"ck_cluster_exporter\",mode=\"idle\"}[$__interval])) by (instance))*100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Mem使用率",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{job=\"ck_cluster_exporter\"} - node_memory_MemAvailable_bytes{job=\"ck_cluster_exporter\"}) / node_memory_MemTotal_bytes{job=\"ck_cluster_exporter\"} * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "磁盘每秒读写速率",
   "type": "graph",
   "description": "Reads completed: 每个磁盘分区每秒读完成次数\n\nWrites completed: 每个磁盘分区每秒写完成次数",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "iops", "label": "读取（-）/写入（+）" }
   ],
   "targets": [
    {
     "expr": "avg(rate(node_disk_reads_completed_total{job=\"ck_cluster_exporter\"}[$__interval])) by (instance)",
     "legendFormat": "{{instance}}_读取"
    },
    {
     "expr": "avg(rate(node_disk_writes_completed_total{job=\"ck_cluster_exporter\"}[$__interval])) by (instance)",
     "legendFormat": "{{instance}}_写入"
    }
   ]
  },
  {
   "title": "磁盘每秒读写容量",
   "type": "graph",
   "description": "Read bytes 每个磁盘分区每秒读取的比特数\n\nWritten bytes 每个磁盘分区每秒写入的比特数",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "Bps", "label": "读取（-）/写入（+）" }
   ],
   "targets": [
    {
     "expr": "avg(rate(node_disk_read_bytes_total{job=\"ck_cluster_exporter\"}[$__interval])) by (instance)",
     "legendFormat": "{{instance}}_读取"
    },
    {
     "expr": "avg(rate(node_disk_written_bytes_total{job=\"ck_cluster_exporter\"}[$__interval])) by (instance)",
     "legendFormat": "{{instance}}_写入"
    }
   ]
  },
  {
   "title": "磁盘每次IO读写耗时",
   "type": "graph",
   "description": "IO time seconds 每个磁盘分区输入/输出操作花费的秒数",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "s", "label": "读取（-）/写入（+）" }
   ],
   "targets": [
    {
     "expr": "avg(rate(node_disk_read_time_seconds_total{job=\"ck_cluster_exporter\"}[$__interval]) / rate(node_disk_reads_completed_total{job=\"ck_cluster_exporter\"}[$__interval])) by (instance)",
     "legendFormat": "{{instance}}_读取"
    },
    {
     "expr": "avg(rate(node_disk_write_time_seconds_total{job=\"ck_cluster_exporter\"}[$__interval]) / rate(node_disk_writes_completed_total{job=\"ck_cluster_exporter\"}[$__interval])) by (instance)",
     "legendFormat": "{{instance}}_写入"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    ProfileEvent_Query s1r1\nFROM $table\n\nWHERE $timeFilter\n\nORDER BY t\n\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(event_time), 30) * 30) * 1000 as t,\n    ProfileEvent_Query s1r1\nFROM system.metric_log\n\nWHERE event_date >= toDate(1664532341) AND event_date <= toDate(1664553941) AND event_time >= toDateTime(1664532341) AND event_time <= toDateTime(1664553941)\n\nORDER BY t",
     "round": "0s",
     "table": "metric_log"
    },
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    ProfileEvent_Query s1r2\nFROM $table\n\nWHERE $timeFilter\n\nORDER BY t\n\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(event_time), 30) * 30) * 1000 as t,\n    ProfileEvent_Query s1r2\nFROM system.metric_log\n\nWHERE event_date >= toDate(1664532341) AND event_date <= toDate(1664553941) AND event_time >= toDateTime(1664532341) AND event_time <= toDateTime(1664553941)\n\nORDER BY t",
     "round": "0s",
     "table": "metric_log"
    },
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    ProfileEvent_Query s2r1\nFROM $table\n\nWHERE $timeFilter\n\nORDER BY t\n\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(event_time), 30) * 30) * 1000 as t,\n    ProfileEvent_Query s2r1\nFROM system.metric_log\n\nWHERE event_date >= toDate(1664532341) AND event_date <= toDate(1664553941) AND event_time >= toDateTime(1664532341) AND event_time <= toDateTime(1664553941)\n\nORDER BY t",
     "round": "0s",
     "table": "metric_log"
    },
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    ProfileEvent_Query s2r2\nFROM $table\n\nWHERE $timeFilter\n\nORDER BY t\n\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(event_time), 30) * 30) * 1000 as t,\n    ProfileEvent_Query s2r2\nFROM system.metric_log\n\nWHERE event_date >= toDate(1664532341) AND event_date <= toDate(1664553941) AND event_time >= toDateTime(1664532341) AND event_time <= toDateTime(1664553941)\n\nORDER BY t",
     "round": "0s",
     "table": "metric_log"
    },
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    ProfileEvent_Query s3r1\nFROM $table\n\nWHERE $timeFilter\n\nORDER BY t\n\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(event_time), 30) * 30) * 1000 as t,\n    ProfileEvent_Query s3r1\nFROM system.metric_log\n\nWHERE event_date >= toDate(1664532341) AND event_date <= toDate(1664553941) AND event_time >= toDateTime(1664532341) AND event_time <= toDateTime(1664553941)\n\nORDER BY t",
     "round": "0s",
     "table": "metric_log"
    },
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    ProfileEvent_Query s3r2\nFROM $table\n\nWHERE $timeFilter\n\nORDER BY t\n\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(event_time), 30) * 30) * 1000 as t,\n    ProfileEvent_Query s3r2\nFROM system.metric_log\n\nWHERE event_date >= toDate(1664532341) AND event_date <= toDate(1664553941) AND event_time >= toDateTime(1664532341) AND event_time <= toDateTime(1664553941)\n\nORDER BY t",
     "round": "0s",
     "table": "metric_log"
    },
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    ProfileEvent_Query s4r1\nFROM $table\n\nWHERE $timeFilter\n\nORDER BY t\n\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(event_time), 30) * 30) * 1000 as t,\n    ProfileEvent_Query s4r1\nFROM system.metric_log\n\nWHERE event_date >= toDate(1664532341) AND event_date <= toDate(1664553941) AND event_time >= toDateTime(1664532341) AND event_time <= toDateTime(1664553941)\n\nORDER BY t",
     "round": "0s",
     "table": "metric_log"
    },
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    ProfileEvent_Query s4r2\nFROM $table\n\nWHERE $timeFilter\n\nORDER BY t\n\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(event_time), 30) * 30) * 1000 as t,\n    ProfileEvent_Query s4r2\nFROM system.metric_log\n\nWHERE event_date >= toDate(1664532341) AND event_date <= toDate(1664553941) AND event_time >= toDateTime(1664532341) AND event_time <= toDateTime(1664553941)\n\nORDER BY t",
     "round": "0s",
     "table": "metric_log"
    },
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    ProfileEvent_Query s5r1\nFROM $table\n\nWHERE $timeFilter\n\nORDER BY t\n\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(event_time), 30) * 30) * 1000 as t,\n    ProfileEvent_Query s5r1\nFROM system.metric_log\n\nWHERE event_date >= toDate(1664532341) AND event_date <= toDate(1664553941) AND event_time >= toDateTime(1664532341) AND event_time <= toDateTime(1664553941)\n\nORDER BY t",
     "round": "0s",
     "table": "metric_log"
    },
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    ProfileEvent_Query s5r2\nFROM $table\n\nWHERE $timeFilter\n\nORDER BY t\n\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(event_time), 30) * 30) * 1000 as t,\n    ProfileEvent_Query s5r2\nFROM system.metric_log\n\nWHERE event_date >= toDate(1664532341) AND event_date <= toDate(1664553941) AND event_time >= toDateTime(1664532341) AND event_time <= toDateTime(1664553941)\n\nORDER BY t",
     "round": "0s",
     "table": "metric_log"
    }
   ]
  },
  {
   "title": "Write Rows Per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short", "label": "row/s" }
   ],
   "targets": [
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    ProfileEvent_InsertedRows s1r1\nFROM $table\n\nWHERE $timeFilter\n\nORDER BY t\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(event_time), 1) * 1) * 1000 as t,\n    ProfileEvent_InsertedRows s1r1\nFROM system.metric_log\n\nWHERE event_date >= toDate(1663926493) AND event_date <= toDate(1663928293) AND event_time >= toDateTime(1663926493) AND event_time <= toDateTime(1663928293)\n\nORDER BY t",
     "round": "0s",
     "table": "metric_log"
    },
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    ProfileEvent_InsertedRows s1r2\nFROM $table\n\nWHERE $timeFilter\n\nORDER BY t\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(event_time), 1) * 1) * 1000 as t,\n    ProfileEvent_InsertedRows s1r2\nFROM system.metric_log\n\nWHERE event_date >= toDate(1663926493) AND event_date <= toDate(1663928293) AND event_time >= toDateTime(1663926493) AND event_time <= toDateTime(1663928293)\n\nORDER BY t",
     "round": "0s",
     "table": "metric_log"
    },
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    ProfileEvent_InsertedRows s2r1\nFROM $table\n\nWHERE $timeFilter\n\nORDER BY t\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(event_time), 1) * 1) * 1000 as t,\n    ProfileEvent_InsertedRows s2r1\nFROM system.metric_log\n\nWHERE event_date >= toDate(1663926493) AND event_date <= toDate(1663928293) AND event_time >= toDateTime(1663926493) AND event_time <= toDateTime(1663928293)\n\nORDER BY t",
     "round": "0s",
     "table": "metric_log"
    },
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    ProfileEvent_InsertedRows s2r2\nFROM $table\n\nWHERE $timeFilter\n\nORDER BY t\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(event_time), 1) * 1) * 1000 as t,\n    ProfileEvent_InsertedRows s2r2\nFROM system.metric_log\n\nWHERE event_date >= toDate(1663926493) AND event_date <= toDate(1663928293) AND event_time >= toDateTime(1663926493) AND event_time <= toDateTime(1663928293)\n\nORDER BY t",
     "round": "0s",
     "table": "metric_log"
    },
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    ProfileEvent_InsertedRows s3r1\nFROM $table\n\nWHERE $timeFilter\n\nORDER BY t\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(event_time), 1) * 1) * 1000 as t,\n    ProfileEvent_InsertedRows s3r1\nFROM system.metric_log\n\nWHERE event_date >= toDate(1663926493) AND event_date <= toDate(1663928293) AND event_time >= toDateTime(1663926493) AND event_time <= toDateTime(1663928293)\n\nORDER BY t",
     "round": "0s",
     "table": "metric_log"
    },
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    ProfileEvent_InsertedRows s3r2\nFROM $table\n\nWHERE $timeFilter\n\nORDER BY t\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(event_time), 1) * 1) * 1000 as t,\n    ProfileEvent_InsertedRows s3r2\nFROM system.metric_log\n\nWHERE event_date >= toDate(1663926493) AND event_date <= toDate(1663928293) AND event_time >= toDateTime(1663926493) AND event_time <= toDateTime(1663928293)\n\nORDER BY t",
     "round": "0s",
     "table": "metric_log"
    },
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    ProfileEvent_InsertedRows s4r1\nFROM $table\n\nWHERE $timeFilter\n\nORDER BY t\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(event_time), 1) * 1) * 1000 as t,\n    ProfileEvent_InsertedRows s4r1\nFROM system.metric_log\n\nWHERE event_date >= toDate(1663926493) AND event_date <= toDate(1663928293) AND event_time >= toDateTime(1663926493) AND event_time <= toDateTime(1663928293)\n\nORDER BY t",
     "round": "0s",
     "table": "metric_log"
    },
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    ProfileEvent_InsertedRows s4r2\nFROM $table\n\nWHERE $timeFilter\n\nORDER BY t\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(event_time), 1) * 1) * 1000 as t,\n    ProfileEvent_InsertedRows s4r2\nFROM system.metric_log\n\nWHERE event_date >= toDate(1663926493) AND event_date <= toDate(1663928293) AND event_time >= toDateTime(1663926493) AND event_time <= toDateTime(1663928293)\n\nORDER BY t",
     "round": "0s",
     "table": "metric_log"
    },
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    ProfileEvent_InsertedRows s5r1\nFROM $table\n\nWHERE $timeFilter\n\nORDER BY t\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(event_time), 1) * 1) * 1000 as t,\n    ProfileEvent_InsertedRows s5r1\nFROM system.metric_log\n\nWHERE event_date >= toDate(1663926493) AND event_date <= toDate(1663928293) AND event_time >= toDateTime(1663926493) AND event_time <= toDateTime(1663928293)\n\nORDER BY t",
     "round": "0s",
     "table": "metric_log"
    },
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    ProfileEvent_InsertedRows s5r2\nFROM $table\n\nWHERE $timeFilter\n\nORDER BY t\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(event_time), 1) * 1) * 1000 as t,\n    ProfileEvent_InsertedRows s5r2\nFROM system.metric_log\n\nWHERE event_date >= toDate(1663926493) AND event_date <= toDate(1663928293) AND event_time >= toDateTime(1663926493) AND event_time <= toDateTime(1663928293)\n\nORDER BY t",
     "round": "0s",
     "table": "metric_log"
    }
   ]
  },
  {
   "title": "Write Bytes Per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    ProfileEvent_InsertedBytes s1r1\nFROM $table\n\nWHERE $timeFilter\n\nORDER BY t\n\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(event_time), 1) * 1) * 1000 as t,\n    ProfileEvent_InsertedBytes s1r1\nFROM system.metric_log\n\nWHERE event_date >= toDate(1663926538) AND event_date <= toDate(1663928338) AND event_time >= toDateTime(1663926538) AND event_time <= toDateTime(1663928338)\n\nORDER BY t",
     "round": "0s",
     "table": "metric_log"
    },
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    ProfileEvent_InsertedBytes s1r2\nFROM $table\n\nWHERE $timeFilter\n\nORDER BY t\n\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(event_time), 1) * 1) * 1000 as t,\n    ProfileEvent_InsertedBytes s1r2\nFROM system.metric_log\n\nWHERE event_date >= toDate(1663926538) AND event_date <= toDate(1663928338) AND event_time >= toDateTime(1663926538) AND event_time <= toDateTime(1663928338)\n\nORDER BY t",
     "round": "0s",
     "table": "metric_log"
    },
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    ProfileEvent_InsertedBytes s2r1\nFROM $table\n\nWHERE $timeFilter\n\nORDER BY t\n\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(event_time), 1) * 1) * 1000 as t,\n    ProfileEvent_InsertedBytes s2r1\nFROM system.metric_log\n\nWHERE event_date >= toDate(1663926538) AND event_date <= toDate(1663928338) AND event_time >= toDateTime(1663926538) AND event_time <= toDateTime(1663928338)\n\nORDER BY t",
     "round": "0s",
     "table": "metric_log"
    },
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    ProfileEvent_InsertedBytes s2r2\nFROM $table\n\nWHERE $timeFilter\n\nORDER BY t\n\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(event_time), 1) * 1) * 1000 as t,\n    ProfileEvent_InsertedBytes s2r2\nFROM system.metric_log\n\nWHERE event_date >= toDate(1663926538) AND event_date <= toDate(1663928338) AND event_time >= toDateTime(1663926538) AND event_time <= toDateTime(1663928338)\n\nORDER BY t",
     "round": "0s",
     "table": "metric_log"
    },
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    ProfileEvent_InsertedBytes s3r1\nFROM $table\n\nWHERE $timeFilter\n\nORDER BY t\n\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(event_time), 1) * 1) * 1000 as t,\n    ProfileEvent_InsertedBytes s3r1\nFROM system.metric_log\n\nWHERE event_date >= toDate(1663926538) AND event_date <= toDate(1663928338) AND event_time >= toDateTime(1663926538) AND event_time <= toDateTime(1663928338)\n\nORDER BY t",
     "round": "0s",
     "table": "metric_log"
    },
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    ProfileEvent_InsertedBytes s3r2\nFROM $table\n\nWHERE $timeFilter\n\nORDER BY t\n\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(event_time), 1) * 1) * 1000 as t,\n    ProfileEvent_InsertedBytes s3r2\nFROM system.metric_log\n\nWHERE event_date >= toDate(1663926538) AND event_date <= toDate(1663928338) AND event_time >= toDateTime(1663926538) AND event_time <= toDateTime(1663928338)\n\nORDER BY t",
     "round": "0s",
     "table": "metric_log"
    },
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    ProfileEvent_InsertedBytes s4r1\nFROM $table\n\nWHERE $timeFilter\n\nORDER BY t\n\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(event_time), 1) * 1) * 1000 as t,\n    ProfileEvent_InsertedBytes s4r1\nFROM system.metric_log\n\nWHERE event_date >= toDate(1663926538) AND event_date <= toDate(1663928338) AND event_time >= toDateTime(1663926538) AND event_time <= toDateTime(1663928338)\n\nORDER BY t",
     "round": "0s",
     "table": "metric_log"
    },
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    ProfileEvent_InsertedBytes s4r2\nFROM $table\n\nWHERE $timeFilter\n\nORDER BY t\n\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(event_time), 1) * 1) * 1000 as t,\n    ProfileEvent_InsertedBytes s4r2\nFROM system.metric_log\n\nWHERE event_date >= toDate(1663926538) AND event_date <= toDate(1663928338) AND event_time >= toDateTime(1663926538) AND event_time <= toDateTime(1663928338)\n\nORDER BY t",
     "round": "0s",
     "table": "metric_log"
    },
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    ProfileEvent_InsertedBytes s5r1\nFROM $table\n\nWHERE $timeFilter\n\nORDER BY t\n\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(event_time), 1) * 1) * 1000 as t,\n    ProfileEvent_InsertedBytes s5r1\nFROM system.metric_log\n\nWHERE event_date >= toDate(1663926538) AND event_date <= toDate(1663928338) AND event_time >= toDateTime(1663926538) AND event_time <= toDateTime(1663928338)\n\nORDER BY t",
     "round": "0s",
     "table": "metric_log"
    },
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    ProfileEvent_InsertedBytes s5r2\nFROM $table\n\nWHERE $timeFilter\n\nORDER BY t\n\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(event_time), 1) * 1) * 1000 as t,\n    ProfileEvent_InsertedBytes s5r2\nFROM system.metric_log\n\nWHERE event_date >= toDate(1663926538) AND event_date <= toDate(1663928338) AND event_time >= toDateTime(1663926538) AND event_time <= toDateTime(1663928338)\n\nORDER BY t",
     "round": "0s",
     "table": "metric_log"
    }
   ]
  },
  {
   "title": "Top 20 slow queries",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font><br />    <font color=\"navajowhite\">rand</font>() <font color=\"darkorange\">as</font> t,<br />    <font color=\"navajowhite\">substring</font>(query,  <font color=\"cornflowerblue\">1</font>,  <font color=\"cornflowerblue\">70</font>) <font color=\"darkorange\">AS</font> query,<br />    <font color=\"navajowhite\">avg</font>(query_duration_ms) duration,<br />    <font color=\"navajowhite\">count</font>() <font color=\"navajowhite\">count</font><br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br /><font color=\"darkorange\">WHERE</font><br />    <font color=\"darkcyan\">$timeFilter</font><br />    <font color=\"yellow\">AND</font> <font color=\"darkorange\">type</font> <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$type</font>)<br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br />    <font color=\"yellow\">and</font>(<font color=\"lightgreen\">'$query_type'</font> <font color=\"yellow\">=</font> <font color=\"lightgreen\">'all'</font> <font color=\"yellow\">or</font>(positionCaseInsensitive(query,  <font color=\"lightgreen\">'$query_type'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font>))<br /><font color=\"darkorange\">GROUP BY</font> query<br /><font color=\"darkorange\">ORDER BY</font> duration <font color=\"darkorange\">desc</font><br /><font color=\"darkorange\">LIMIT</font> <font color=\"darkcyan\">$top</font>",
     "query": "SELECT\n    query,\n    avg(query_duration_ms) duration,\n    count() count\nFROM system.query_log\nWHERE\n    $timeFilter\n    AND type = 2\n    and initial_user ='aiops'\n    and positionCaseInsensitive(query,  'select') = 1\nGROUP BY query\nORDER BY duration desc\nLIMIT 20",
     "rawQuery": "SELECT\n    query,\n    avg(query_duration_ms) duration,\n    count() count\nFROM system.query_log\nWHERE\n    event_date >= toDate(1665049763) AND event_date <= toDate(1665053363) AND event_time >= toDateTime(1665049763) AND event_time <= toDateTime(1665053363)\n    AND type = 2\n    and initial_user ='aiops'\n    and positionCaseInsensitive(query,  'select') = 1\nGROUP BY query\nORDER BY duration desc\nLIMIT 20",
     "round": "0s",
     "table": "query_log"
    },
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font><br />    <font color=\"navajowhite\">rand</font>() <font color=\"darkorange\">as</font> t,<br />    <font color=\"navajowhite\">substring</font>(query,  <font color=\"cornflowerblue\">1</font>,  <font color=\"cornflowerblue\">70</font>) <font color=\"darkorange\">AS</font> query,<br />    <font color=\"navajowhite\">avg</font>(query_duration_ms) duration,<br />    <font color=\"navajowhite\">count</font>() <font color=\"navajowhite\">count</font><br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br /><font color=\"darkorange\">WHERE</font><br />    <font color=\"darkcyan\">$timeFilter</font><br />    <font color=\"yellow\">AND</font> <font color=\"darkorange\">type</font> <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$type</font>)<br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br />    <font color=\"yellow\">and</font>(<font color=\"lightgreen\">'$query_type'</font> <font color=\"yellow\">=</font> <font color=\"lightgreen\">'all'</font> <font color=\"yellow\">or</font>(positionCaseInsensitive(query,  <font color=\"lightgreen\">'$query_type'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font>))<br /><font color=\"darkorange\">GROUP BY</font> query<br /><font color=\"darkorange\">ORDER BY</font> duration <font color=\"darkorange\">desc</font><br /><font color=\"darkorange\">LIMIT</font> <font color=\"darkcyan\">$top</font>",
     "query": "SELECT\n    query,\n    avg(query_duration_ms) duration,\n    count() count\nFROM system.query_log\nWHERE\n    $timeFilter\n    AND type = 2\n    and initial_user ='aiops'\n    and positionCaseInsensitive(query,  'select') = 1\nGROUP BY query\nORDER BY duration desc\nLIMIT 20",
     "rawQuery": "SELECT\n    query,\n    avg(query_duration_ms) duration,\n    count() count\nFROM system.query_log\nWHERE\n    event_date >= toDate(1665049763) AND event_date <= toDate(1665053363) AND event_time >= toDateTime(1665049763) AND event_time <= toDateTime(1665053363)\n    AND type = 2\n    and initial_user ='aiops'\n    and positionCaseInsensitive(query,  'select') = 1\nGROUP BY query\nORDER BY duration desc\nLIMIT 20",
     "round": "0s",
     "table": "query_log"
    },
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font><br />    <font color=\"navajowhite\">rand</font>() <font color=\"darkorange\">as</font> t,<br />    <font color=\"navajowhite\">substring</font>(query,  <font color=\"cornflowerblue\">1</font>,  <font color=\"cornflowerblue\">70</font>) <font color=\"darkorange\">AS</font> query,<br />    <font color=\"navajowhite\">avg</font>(query_duration_ms) duration,<br />    <font color=\"navajowhite\">count</font>() <font color=\"navajowhite\">count</font><br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br /><font color=\"darkorange\">WHERE</font><br />    <font color=\"darkcyan\">$timeFilter</font><br />    <font color=\"yellow\">AND</font> <font color=\"darkorange\">type</font> <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$type</font>)<br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br />    <font color=\"yellow\">and</font>(<font color=\"lightgreen\">'$query_type'</font> <font color=\"yellow\">=</font> <font color=\"lightgreen\">'all'</font> <font color=\"yellow\">or</font>(positionCaseInsensitive(query,  <font color=\"lightgreen\">'$query_type'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font>))<br /><font color=\"darkorange\">GROUP BY</font> query<br /><font color=\"darkorange\">ORDER BY</font> duration <font color=\"darkorange\">desc</font><br /><font color=\"darkorange\">LIMIT</font> <font color=\"darkcyan\">$top</font>",
     "query": "SELECT\n    query,\n    avg(query_duration_ms) duration,\n    count() count\nFROM system.query_log\nWHERE\n    $timeFilter\n    AND type = 2\n    and initial_user ='aiops'\n    and positionCaseInsensitive(query,  'select') = 1\nGROUP BY query\nORDER BY duration desc\nLIMIT 20",
     "rawQuery": "SELECT\n    query,\n    avg(query_duration_ms) duration,\n    count() count\nFROM system.query_log\nWHERE\n    event_date >= toDate(1665049763) AND event_date <= toDate(1665053363) AND event_time >= toDateTime(1665049763) AND event_time <= toDateTime(1665053363)\n    AND type = 2\n    and initial_user ='aiops'\n    and positionCaseInsensitive(query,  'select') = 1\nGROUP BY query\nORDER BY duration desc\nLIMIT 20",
     "round": "0s",
     "table": "query_log"
    },
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font><br />    <font color=\"navajowhite\">rand</font>() <font color=\"darkorange\">as</font> t,<br />    <font color=\"navajowhite\">substring</font>(query,  <font color=\"cornflowerblue\">1</font>,  <font color=\"cornflowerblue\">70</font>) <font color=\"darkorange\">AS</font> query,<br />    <font color=\"navajowhite\">avg</font>(query_duration_ms) duration,<br />    <font color=\"navajowhite\">count</font>() <font color=\"navajowhite\">count</font><br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br /><font color=\"darkorange\">WHERE</font><br />    <font color=\"darkcyan\">$timeFilter</font><br />    <font color=\"yellow\">AND</font> <font color=\"darkorange\">type</font> <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$type</font>)<br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br />    <font color=\"yellow\">and</font>(<font color=\"lightgreen\">'$query_type'</font> <font color=\"yellow\">=</font> <font color=\"lightgreen\">'all'</font> <font color=\"yellow\">or</font>(positionCaseInsensitive(query,  <font color=\"lightgreen\">'$query_type'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font>))<br /><font color=\"darkorange\">GROUP BY</font> query<br /><font color=\"darkorange\">ORDER BY</font> duration <font color=\"darkorange\">desc</font><br /><font color=\"darkorange\">LIMIT</font> <font color=\"darkcyan\">$top</font>",
     "query": "SELECT\n    query,\n    avg(query_duration_ms) duration,\n    count() count\nFROM system.query_log\nWHERE\n    $timeFilter\n    AND type = 2\n    and initial_user ='aiops'\n    and positionCaseInsensitive(query,  'select') = 1\nGROUP BY query\nORDER BY duration desc\nLIMIT 20",
     "rawQuery": "SELECT\n    query,\n    avg(query_duration_ms) duration,\n    count() count\nFROM system.query_log\nWHERE\n    event_date >= toDate(1665049763) AND event_date <= toDate(1665053363) AND event_time >= toDateTime(1665049763) AND event_time <= toDateTime(1665053363)\n    AND type = 2\n    and initial_user ='aiops'\n    and positionCaseInsensitive(query,  'select') = 1\nGROUP BY query\nORDER BY duration desc\nLIMIT 20",
     "round": "0s",
     "table": "query_log"
    },
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font><br />    <font color=\"navajowhite\">rand</font>() <font color=\"darkorange\">as</font> t,<br />    <font color=\"navajowhite\">substring</font>(query,  <font color=\"cornflowerblue\">1</font>,  <font color=\"cornflowerblue\">70</font>) <font color=\"darkorange\">AS</font> query,<br />    <font color=\"navajowhite\">avg</font>(query_duration_ms) duration,<br />    <font color=\"navajowhite\">count</font>() <font color=\"navajowhite\">count</font><br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br /><font color=\"darkorange\">WHERE</font><br />    <font color=\"darkcyan\">$timeFilter</font><br />    <font color=\"yellow\">AND</font> <font color=\"darkorange\">type</font> <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$type</font>)<br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br />    <font color=\"yellow\">and</font>(<font color=\"lightgreen\">'$query_type'</font> <font color=\"yellow\">=</font> <font color=\"lightgreen\">'all'</font> <font color=\"yellow\">or</font>(positionCaseInsensitive(query,  <font color=\"lightgreen\">'$query_type'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font>))<br /><font color=\"darkorange\">GROUP BY</font> query<br /><font color=\"darkorange\">ORDER BY</font> duration <font color=\"darkorange\">desc</font><br /><font color=\"darkorange\">LIMIT</font> <font color=\"darkcyan\">$top</font>",
     "query": "SELECT\n    query,\n    avg(query_duration_ms) duration,\n    count() count\nFROM system.query_log\nWHERE\n    $timeFilter\n    AND type = 2\n    and initial_user ='aiops'\n    and positionCaseInsensitive(query,  'select') = 1\nGROUP BY query\nORDER BY duration desc\nLIMIT 20",
     "rawQuery": "SELECT\n    query,\n    avg(query_duration_ms) duration,\n    count() count\nFROM system.query_log\nWHERE\n    event_date >= toDate(1665049763) AND event_date <= toDate(1665053363) AND event_time >= toDateTime(1665049763) AND event_time <= toDateTime(1665053363)\n    AND type = 2\n    and initial_user ='aiops'\n    and positionCaseInsensitive(query,  'select') = 1\nGROUP BY query\nORDER BY duration desc\nLIMIT 20",
     "round": "0s",
     "table": "query_log"
    },
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font><br />    <font color=\"navajowhite\">rand</font>() <font color=\"darkorange\">as</font> t,<br />    <font color=\"navajowhite\">substring</font>(query,  <font color=\"cornflowerblue\">1</font>,  <font color=\"cornflowerblue\">70</font>) <font color=\"darkorange\">AS</font> query,<br />    <font color=\"navajowhite\">avg</font>(query_duration_ms) duration,<br />    <font color=\"navajowhite\">count</font>() <font color=\"navajowhite\">count</font><br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br /><font color=\"darkorange\">WHERE</font><br />    <font color=\"darkcyan\">$timeFilter</font><br />    <font color=\"yellow\">AND</font> <font color=\"darkorange\">type</font> <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$type</font>)<br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br />    <font color=\"yellow\">and</font>(<font color=\"lightgreen\">'$query_type'</font> <font color=\"yellow\">=</font> <font color=\"lightgreen\">'all'</font> <font color=\"yellow\">or</font>(positionCaseInsensitive(query,  <font color=\"lightgreen\">'$query_type'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font>))<br /><font color=\"darkorange\">GROUP BY</font> query<br /><font color=\"darkorange\">ORDER BY</font> duration <font color=\"darkorange\">desc</font><br /><font color=\"darkorange\">LIMIT</font> <font color=\"darkcyan\">$top</font>",
     "query": "SELECT\n    query,\n    avg(query_duration_ms) duration,\n    count() count\nFROM system.query_log\nWHERE\n    $timeFilter\n    AND type = 2\n    and initial_user ='aiops'\n    and positionCaseInsensitive(query,  'select') = 1\nGROUP BY query\nORDER BY duration desc\nLIMIT 20",
     "rawQuery": "SELECT\n    query,\n    avg(query_duration_ms) duration,\n    count() count\nFROM system.query_log\nWHERE\n    event_date >= toDate(1665049763) AND event_date <= toDate(1665053363) AND event_time >= toDateTime(1665049763) AND event_time <= toDateTime(1665053363)\n    AND type = 2\n    and initial_user ='aiops'\n    and positionCaseInsensitive(query,  'select') = 1\nGROUP BY query\nORDER BY duration desc\nLIMIT 20",
     "round": "0s",
     "table": "query_log"
    },
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font><br />    <font color=\"navajowhite\">rand</font>() <font color=\"darkorange\">as</font> t,<br />    <font color=\"navajowhite\">substring</font>(query,  <font color=\"cornflowerblue\">1</font>,  <font color=\"cornflowerblue\">70</font>) <font color=\"darkorange\">AS</font> query,<br />    <font color=\"navajowhite\">avg</font>(query_duration_ms) duration,<br />    <font color=\"navajowhite\">count</font>() <font color=\"navajowhite\">count</font><br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br /><font color=\"darkorange\">WHERE</font><br />    <font color=\"darkcyan\">$timeFilter</font><br />    <font color=\"yellow\">AND</font> <font color=\"darkorange\">type</font> <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$type</font>)<br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br />    <font color=\"yellow\">and</font>(<font color=\"lightgreen\">'$query_type'</font> <font color=\"yellow\">=</font> <font color=\"lightgreen\">'all'</font> <font color=\"yellow\">or</font>(positionCaseInsensitive(query,  <font color=\"lightgreen\">'$query_type'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font>))<br /><font color=\"darkorange\">GROUP BY</font> query<br /><font color=\"darkorange\">ORDER BY</font> duration <font color=\"darkorange\">desc</font><br /><font color=\"darkorange\">LIMIT</font> <font color=\"darkcyan\">$top</font>",
     "query": "SELECT\n    query,\n    avg(query_duration_ms) duration,\n    count() count\nFROM system.query_log\nWHERE\n    $timeFilter\n    AND type = 2\n    and initial_user ='aiops'\n    and positionCaseInsensitive(query,  'select') = 1\nGROUP BY query\nORDER BY duration desc\nLIMIT 20",
     "rawQuery": "SELECT\n    query,\n    avg(query_duration_ms) duration,\n    count() count\nFROM system.query_log\nWHERE\n    event_date >= toDate(1665049763) AND event_date <= toDate(1665053363) AND event_time >= toDateTime(1665049763) AND event_time <= toDateTime(1665053363)\n    AND type = 2\n    and initial_user ='aiops'\n    and positionCaseInsensitive(query,  'select') = 1\nGROUP BY query\nORDER BY duration desc\nLIMIT 20",
     "round": "0s",
     "table": "query_log"
    },
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font><br />    <font color=\"navajowhite\">rand</font>() <font color=\"darkorange\">as</font> t,<br />    <font color=\"navajowhite\">substring</font>(query,  <font color=\"cornflowerblue\">1</font>,  <font color=\"cornflowerblue\">70</font>) <font color=\"darkorange\">AS</font> query,<br />    <font color=\"navajowhite\">avg</font>(query_duration_ms) duration,<br />    <font color=\"navajowhite\">count</font>() <font color=\"navajowhite\">count</font><br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br /><font color=\"darkorange\">WHERE</font><br />    <font color=\"darkcyan\">$timeFilter</font><br />    <font color=\"yellow\">AND</font> <font color=\"darkorange\">type</font> <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$type</font>)<br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br />    <font color=\"yellow\">and</font>(<font color=\"lightgreen\">'$query_type'</font> <font color=\"yellow\">=</font> <font color=\"lightgreen\">'all'</font> <font color=\"yellow\">or</font>(positionCaseInsensitive(query,  <font color=\"lightgreen\">'$query_type'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font>))<br /><font color=\"darkorange\">GROUP BY</font> query<br /><font color=\"darkorange\">ORDER BY</font> duration <font color=\"darkorange\">desc</font><br /><font color=\"darkorange\">LIMIT</font> <font color=\"darkcyan\">$top</font>",
     "query": "SELECT\n    query,\n    avg(query_duration_ms) duration,\n    count() count\nFROM system.query_log\nWHERE\n    $timeFilter\n    AND type = 2\n    and initial_user ='aiops'\n    and positionCaseInsensitive(query,  'select') = 1\nGROUP BY query\nORDER BY duration desc\nLIMIT 20",
     "rawQuery": "SELECT\n    query,\n    avg(query_duration_ms) duration,\n    count() count\nFROM system.query_log\nWHERE\n    event_date >= toDate(1665049763) AND event_date <= toDate(1665053363) AND event_time >= toDateTime(1665049763) AND event_time <= toDateTime(1665053363)\n    AND type = 2\n    and initial_user ='aiops'\n    and positionCaseInsensitive(query,  'select') = 1\nGROUP BY query\nORDER BY duration desc\nLIMIT 20",
     "round": "0s",
     "table": "query_log"
    },
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font><br />    <font color=\"navajowhite\">rand</font>() <font color=\"darkorange\">as</font> t,<br />    <font color=\"navajowhite\">substring</font>(query,  <font color=\"cornflowerblue\">1</font>,  <font color=\"cornflowerblue\">70</font>) <font color=\"darkorange\">AS</font> query,<br />    <font color=\"navajowhite\">avg</font>(query_duration_ms) duration,<br />    <font color=\"navajowhite\">count</font>() <font color=\"navajowhite\">count</font><br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br /><font color=\"darkorange\">WHERE</font><br />    <font color=\"darkcyan\">$timeFilter</font><br />    <font color=\"yellow\">AND</font> <font color=\"darkorange\">type</font> <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$type</font>)<br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br />    <font color=\"yellow\">and</font>(<font color=\"lightgreen\">'$query_type'</font> <font color=\"yellow\">=</font> <font color=\"lightgreen\">'all'</font> <font color=\"yellow\">or</font>(positionCaseInsensitive(query,  <font color=\"lightgreen\">'$query_type'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font>))<br /><font color=\"darkorange\">GROUP BY</font> query<br /><font color=\"darkorange\">ORDER BY</font> duration <font color=\"darkorange\">desc</font><br /><font color=\"darkorange\">LIMIT</font> <font color=\"darkcyan\">$top</font>",
     "query": "SELECT\n    query,\n    avg(query_duration_ms) duration,\n    count() count\nFROM system.query_log\nWHERE\n    $timeFilter\n    AND type = 2\n    and initial_user ='aiops'\n    and positionCaseInsensitive(query,  'select') = 1\nGROUP BY query\nORDER BY duration desc\nLIMIT 20",
     "rawQuery": "SELECT\n    query,\n    avg(query_duration_ms) duration,\n    count() count\nFROM system.query_log\nWHERE\n    event_date >= toDate(1665049763) AND event_date <= toDate(1665053363) AND event_time >= toDateTime(1665049763) AND event_time <= toDateTime(1665053363)\n    AND type = 2\n    and initial_user ='aiops'\n    and positionCaseInsensitive(query,  'select') = 1\nGROUP BY query\nORDER BY duration desc\nLIMIT 20",
     "round": "0s",
     "table": "query_log"
    },
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font><br />    <font color=\"navajowhite\">rand</font>() <font color=\"darkorange\">as</font> t,<br />    <font color=\"navajowhite\">substring</font>(query,  <font color=\"cornflowerblue\">1</font>,  <font color=\"cornflowerblue\">70</font>) <font color=\"darkorange\">AS</font> query,<br />    <font color=\"navajowhite\">avg</font>(query_duration_ms) duration,<br />    <font color=\"navajowhite\">count</font>() <font color=\"navajowhite\">count</font><br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br /><font color=\"darkorange\">WHERE</font><br />    <font color=\"darkcyan\">$timeFilter</font><br />    <font color=\"yellow\">AND</font> <font color=\"darkorange\">type</font> <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$type</font>)<br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br />    <font color=\"yellow\">and</font>(<font color=\"lightgreen\">'$query_type'</font> <font color=\"yellow\">=</font> <font color=\"lightgreen\">'all'</font> <font color=\"yellow\">or</font>(positionCaseInsensitive(query,  <font color=\"lightgreen\">'$query_type'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font>))<br /><font color=\"darkorange\">GROUP BY</font> query<br /><font color=\"darkorange\">ORDER BY</font> duration <font color=\"darkorange\">desc</font><br /><font color=\"darkorange\">LIMIT</font> <font color=\"darkcyan\">$top</font>",
     "query": "SELECT\n    query,\n    avg(query_duration_ms) duration,\n    count() count\nFROM system.query_log\nWHERE\n    $timeFilter\n    AND type = 2\n    and initial_user ='aiops'\n    and positionCaseInsensitive(query,  'select') = 1\nGROUP BY query\nORDER BY duration desc\nLIMIT 20",
     "rawQuery": "SELECT\n    query,\n    avg(query_duration_ms) duration,\n    count() count\nFROM system.query_log\nWHERE\n    event_date >= toDate(1665049763) AND event_date <= toDate(1665053363) AND event_time >= toDateTime(1665049763) AND event_time <= toDateTime(1665053363)\n    AND type = 2\n    and initial_user ='aiops'\n    and positionCaseInsensitive(query,  'select') = 1\nGROUP BY query\nORDER BY duration desc\nLIMIT 20",
     "round": "0s",
     "table": "query_log"
    }
   ]
  },
  {
   "title": "Top 20 memory consumers",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font><br />    <font color=\"navajowhite\">rand</font>() <font color=\"darkorange\">as</font> t,<br />    <font color=\"navajowhite\">substring</font>(query,  <font color=\"cornflowerblue\">1</font>,  <font color=\"cornflowerblue\">70</font>) <font color=\"darkorange\">AS</font> query,<br />    <font color=\"navajowhite\">avg</font>(memory_usage) usage,<br />    <font color=\"navajowhite\">count</font>() <font color=\"navajowhite\">count</font><br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br /><font color=\"darkorange\">WHERE</font><br />    <font color=\"darkcyan\">$timeFilter</font><br />    <font color=\"yellow\">AND</font> <font color=\"darkorange\">type</font> <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$type</font>)<br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br />    <font color=\"yellow\">and</font>(<font color=\"lightgreen\">'$query_type'</font> <font color=\"yellow\">=</font> <font color=\"lightgreen\">'all'</font> <font color=\"yellow\">or</font>(positionCaseInsensitive(query,  <font color=\"lightgreen\">'$query_type'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font>))<br /><font color=\"darkorange\">GROUP BY</font> query<br /><font color=\"darkorange\">ORDER BY</font> usage <font color=\"darkorange\">desc</font><br /><font color=\"darkorange\">LIMIT</font> <font color=\"darkcyan\">$top</font>",
     "query": "SELECT\n    query,\n    avg(memory_usage) usage,\n    count() count\nFROM system.query_log\nWHERE\n    $timeFilter\n    AND type in (2,4)\n    and initial_user ='aiops'\n    and((positionCaseInsensitive(query,  'insert') = 1) or (positionCaseInsensitive(query,  'select') = 1))\nGROUP BY query\nORDER BY usage desc\nLIMIT 20",
     "rawQuery": "SELECT\n    query,\n    avg(memory_usage) usage,\n    count() count\nFROM system.query_log\nWHERE\n    event_date >= toDate(1665049826) AND event_date <= toDate(1665053426) AND event_time >= toDateTime(1665049826) AND event_time <= toDateTime(1665053426)\n    AND type in (2,4)\n    and initial_user ='aiops'\n    and((positionCaseInsensitive(query,  'insert') = 1) or (positionCaseInsensitive(query,  'select') = 1))\nGROUP BY query\nORDER BY usage desc\nLIMIT 20",
     "round": "0s",
     "table": "query_log"
    },
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font><br />    <font color=\"navajowhite\">rand</font>() <font color=\"darkorange\">as</font> t,<br />    <font color=\"navajowhite\">substring</font>(query,  <font color=\"cornflowerblue\">1</font>,  <font color=\"cornflowerblue\">70</font>) <font color=\"darkorange\">AS</font> query,<br />    <font color=\"navajowhite\">avg</font>(memory_usage) usage,<br />    <font color=\"navajowhite\">count</font>() <font color=\"navajowhite\">count</font><br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br /><font color=\"darkorange\">WHERE</font><br />    <font color=\"darkcyan\">$timeFilter</font><br />    <font color=\"yellow\">AND</font> <font color=\"darkorange\">type</font> <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$type</font>)<br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br />    <font color=\"yellow\">and</font>(<font color=\"lightgreen\">'$query_type'</font> <font color=\"yellow\">=</font> <font color=\"lightgreen\">'all'</font> <font color=\"yellow\">or</font>(positionCaseInsensitive(query,  <font color=\"lightgreen\">'$query_type'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font>))<br /><font color=\"darkorange\">GROUP BY</font> query<br /><font color=\"darkorange\">ORDER BY</font> usage <font color=\"darkorange\">desc</font><br /><font color=\"darkorange\">LIMIT</font> <font color=\"darkcyan\">$top</font>",
     "query": "SELECT\n    query,\n    avg(memory_usage) usage,\n    count() count\nFROM system.query_log\nWHERE\n    $timeFilter\n    AND type in (2,4)\n    and initial_user ='aiops'\n    and((positionCaseInsensitive(query,  'insert') = 1) or (positionCaseInsensitive(query,  'select') = 1))\nGROUP BY query\nORDER BY usage desc\nLIMIT 20",
     "rawQuery": "SELECT\n    query,\n    avg(memory_usage) usage,\n    count() count\nFROM system.query_log\nWHERE\n    event_date >= toDate(1665049826) AND event_date <= toDate(1665053426) AND event_time >= toDateTime(1665049826) AND event_time <= toDateTime(1665053426)\n    AND type in (2,4)\n    and initial_user ='aiops'\n    and((positionCaseInsensitive(query,  'insert') = 1) or (positionCaseInsensitive(query,  'select') = 1))\nGROUP BY query\nORDER BY usage desc\nLIMIT 20",
     "round": "0s",
     "table": "query_log"
    },
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font><br />    <font color=\"navajowhite\">rand</font>() <font color=\"darkorange\">as</font> t,<br />    <font color=\"navajowhite\">substring</font>(query,  <font color=\"cornflowerblue\">1</font>,  <font color=\"cornflowerblue\">70</font>) <font color=\"darkorange\">AS</font> query,<br />    <font color=\"navajowhite\">avg</font>(memory_usage) usage,<br />    <font color=\"navajowhite\">count</font>() <font color=\"navajowhite\">count</font><br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br /><font color=\"darkorange\">WHERE</font><br />    <font color=\"darkcyan\">$timeFilter</font><br />    <font color=\"yellow\">AND</font> <font color=\"darkorange\">type</font> <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$type</font>)<br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br />    <font color=\"yellow\">and</font>(<font color=\"lightgreen\">'$query_type'</font> <font color=\"yellow\">=</font> <font color=\"lightgreen\">'all'</font> <font color=\"yellow\">or</font>(positionCaseInsensitive(query,  <font color=\"lightgreen\">'$query_type'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font>))<br /><font color=\"darkorange\">GROUP BY</font> query<br /><font color=\"darkorange\">ORDER BY</font> usage <font color=\"darkorange\">desc</font><br /><font color=\"darkorange\">LIMIT</font> <font color=\"darkcyan\">$top</font>",
     "query": "SELECT\n    query,\n    avg(memory_usage) usage,\n    count() count\nFROM system.query_log\nWHERE\n    $timeFilter\n    AND type in (2,4)\n    and initial_user ='aiops'\n    and((positionCaseInsensitive(query,  'insert') = 1) or (positionCaseInsensitive(query,  'select') = 1))\nGROUP BY query\nORDER BY usage desc\nLIMIT 20",
     "rawQuery": "SELECT\n    query,\n    avg(memory_usage) usage,\n    count() count\nFROM system.query_log\nWHERE\n    event_date >= toDate(1665049826) AND event_date <= toDate(1665053426) AND event_time >= toDateTime(1665049826) AND event_time <= toDateTime(1665053426)\n    AND type in (2,4)\n    and initial_user ='aiops'\n    and((positionCaseInsensitive(query,  'insert') = 1) or (positionCaseInsensitive(query,  'select') = 1))\nGROUP BY query\nORDER BY usage desc\nLIMIT 20",
     "round": "0s",
     "table": "query_log"
    },
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font><br />    <font color=\"navajowhite\">rand</font>() <font color=\"darkorange\">as</font> t,<br />    <font color=\"navajowhite\">substring</font>(query,  <font color=\"cornflowerblue\">1</font>,  <font color=\"cornflowerblue\">70</font>) <font color=\"darkorange\">AS</font> query,<br />    <font color=\"navajowhite\">avg</font>(memory_usage) usage,<br />    <font color=\"navajowhite\">count</font>() <font color=\"navajowhite\">count</font><br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br /><font color=\"darkorange\">WHERE</font><br />    <font color=\"darkcyan\">$timeFilter</font><br />    <font color=\"yellow\">AND</font> <font color=\"darkorange\">type</font> <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$type</font>)<br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br />    <font color=\"yellow\">and</font>(<font color=\"lightgreen\">'$query_type'</font> <font color=\"yellow\">=</font> <font color=\"lightgreen\">'all'</font> <font color=\"yellow\">or</font>(positionCaseInsensitive(query,  <font color=\"lightgreen\">'$query_type'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font>))<br /><font color=\"darkorange\">GROUP BY</font> query<br /><font color=\"darkorange\">ORDER BY</font> usage <font color=\"darkorange\">desc</font><br /><font color=\"darkorange\">LIMIT</font> <font color=\"darkcyan\">$top</font>",
     "query": "SELECT\n    query,\n    avg(memory_usage) usage,\n    count() count\nFROM system.query_log\nWHERE\n    $timeFilter\n    AND type in (2,4)\n    and initial_user ='aiops'\n    and((positionCaseInsensitive(query,  'insert') = 1) or (positionCaseInsensitive(query,  'select') = 1))\nGROUP BY query\nORDER BY usage desc\nLIMIT 20",
     "rawQuery": "SELECT\n    query,\n    avg(memory_usage) usage,\n    count() count\nFROM system.query_log\nWHERE\n    event_date >= toDate(1665049826) AND event_date <= toDate(1665053426) AND event_time >= toDateTime(1665049826) AND event_time <= toDateTime(1665053426)\n    AND type in (2,4)\n    and initial_user ='aiops'\n    and((positionCaseInsensitive(query,  'insert') = 1) or (positionCaseInsensitive(query,  'select') = 1))\nGROUP BY query\nORDER BY usage desc\nLIMIT 20",
     "round": "0s",
     "table": "query_log"
    },
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font><br />    <font color=\"navajowhite\">rand</font>() <font color=\"darkorange\">as</font> t,<br />    <font color=\"navajowhite\">substring</font>(query,  <font color=\"cornflowerblue\">1</font>,  <font color=\"cornflowerblue\">70</font>) <font color=\"darkorange\">AS</font> query,<br />    <font color=\"navajowhite\">avg</font>(memory_usage) usage,<br />    <font color=\"navajowhite\">count</font>() <font color=\"navajowhite\">count</font><br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br /><font color=\"darkorange\">WHERE</font><br />    <font color=\"darkcyan\">$timeFilter</font><br />    <font color=\"yellow\">AND</font> <font color=\"darkorange\">type</font> <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$type</font>)<br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br />    <font color=\"yellow\">and</font>(<font color=\"lightgreen\">'$query_type'</font> <font color=\"yellow\">=</font> <font color=\"lightgreen\">'all'</font> <font color=\"yellow\">or</font>(positionCaseInsensitive(query,  <font color=\"lightgreen\">'$query_type'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font>))<br /><font color=\"darkorange\">GROUP BY</font> query<br /><font color=\"darkorange\">ORDER BY</font> usage <font color=\"darkorange\">desc</font><br /><font color=\"darkorange\">LIMIT</font> <font color=\"darkcyan\">$top</font>",
     "query": "SELECT\n    query,\n    avg(memory_usage) usage,\n    count() count\nFROM system.query_log\nWHERE\n    $timeFilter\n    AND type in (2,4)\n    and initial_user ='aiops'\n    and((positionCaseInsensitive(query,  'insert') = 1) or (positionCaseInsensitive(query,  'select') = 1))\nGROUP BY query\nORDER BY usage desc\nLIMIT 20",
     "rawQuery": "SELECT\n    query,\n    avg(memory_usage) usage,\n    count() count\nFROM system.query_log\nWHERE\n    event_date >= toDate(1665049826) AND event_date <= toDate(1665053426) AND event_time >= toDateTime(1665049826) AND event_time <= toDateTime(1665053426)\n    AND type in (2,4)\n    and initial_user ='aiops'\n    and((positionCaseInsensitive(query,  'insert') = 1) or (positionCaseInsensitive(query,  'select') = 1))\nGROUP BY query\nORDER BY usage desc\nLIMIT 20",
     "round": "0s",
     "table": "query_log"
    },
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font><br />    <font color=\"navajowhite\">rand</font>() <font color=\"darkorange\">as</font> t,<br />    <font color=\"navajowhite\">substring</font>(query,  <font color=\"cornflowerblue\">1</font>,  <font color=\"cornflowerblue\">70</font>) <font color=\"darkorange\">AS</font> query,<br />    <font color=\"navajowhite\">avg</font>(memory_usage) usage,<br />    <font color=\"navajowhite\">count</font>() <font color=\"navajowhite\">count</font><br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br /><font color=\"darkorange\">WHERE</font><br />    <font color=\"darkcyan\">$timeFilter</font><br />    <font color=\"yellow\">AND</font> <font color=\"darkorange\">type</font> <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$type</font>)<br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br />    <font color=\"yellow\">and</font>(<font color=\"lightgreen\">'$query_type'</font> <font color=\"yellow\">=</font> <font color=\"lightgreen\">'all'</font> <font color=\"yellow\">or</font>(positionCaseInsensitive(query,  <font color=\"lightgreen\">'$query_type'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font>))<br /><font color=\"darkorange\">GROUP BY</font> query<br /><font color=\"darkorange\">ORDER BY</font> usage <font color=\"darkorange\">desc</font><br /><font color=\"darkorange\">LIMIT</font> <font color=\"darkcyan\">$top</font>",
     "query": "SELECT\n    query,\n    avg(memory_usage) usage,\n    count() count\nFROM system.query_log\nWHERE\n    $timeFilter\n    AND type in (2,4)\n    and initial_user ='aiops'\n    and((positionCaseInsensitive(query,  'insert') = 1) or (positionCaseInsensitive(query,  'select') = 1))\nGROUP BY query\nORDER BY usage desc\nLIMIT 20",
     "rawQuery": "SELECT\n    query,\n    avg(memory_usage) usage,\n    count() count\nFROM system.query_log\nWHERE\n    event_date >= toDate(1665049826) AND event_date <= toDate(1665053426) AND event_time >= toDateTime(1665049826) AND event_time <= toDateTime(1665053426)\n    AND type in (2,4)\n    and initial_user ='aiops'\n    and((positionCaseInsensitive(query,  'insert') = 1) or (positionCaseInsensitive(query,  'select') = 1))\nGROUP BY query\nORDER BY usage desc\nLIMIT 20",
     "round": "0s",
     "table": "query_log"
    },
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font><br />    <font color=\"navajowhite\">rand</font>() <font color=\"darkorange\">as</font> t,<br />    <font color=\"navajowhite\">substring</font>(query,  <font color=\"cornflowerblue\">1</font>,  <font color=\"cornflowerblue\">70</font>) <font color=\"darkorange\">AS</font> query,<br />    <font color=\"navajowhite\">avg</font>(memory_usage) usage,<br />    <font color=\"navajowhite\">count</font>() <font color=\"navajowhite\">count</font><br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br /><font color=\"darkorange\">WHERE</font><br />    <font color=\"darkcyan\">$timeFilter</font><br />    <font color=\"yellow\">AND</font> <font color=\"darkorange\">type</font> <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$type</font>)<br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br />    <font color=\"yellow\">and</font>(<font color=\"lightgreen\">'$query_type'</font> <font color=\"yellow\">=</font> <font color=\"lightgreen\">'all'</font> <font color=\"yellow\">or</font>(positionCaseInsensitive(query,  <font color=\"lightgreen\">'$query_type'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font>))<br /><font color=\"darkorange\">GROUP BY</font> query<br /><font color=\"darkorange\">ORDER BY</font> usage <font color=\"darkorange\">desc</font><br /><font color=\"darkorange\">LIMIT</font> <font color=\"darkcyan\">$top</font>",
     "query": "SELECT\n    query,\n    avg(memory_usage) usage,\n    count() count\nFROM system.query_log\nWHERE\n    $timeFilter\n    AND type in (2,4)\n    and initial_user ='aiops'\n    and((positionCaseInsensitive(query,  'insert') = 1) or (positionCaseInsensitive(query,  'select') = 1))\nGROUP BY query\nORDER BY usage desc\nLIMIT 20",
     "rawQuery": "SELECT\n    query,\n    avg(memory_usage) usage,\n    count() count\nFROM system.query_log\nWHERE\n    event_date >= toDate(1665049826) AND event_date <= toDate(1665053426) AND event_time >= toDateTime(1665049826) AND event_time <= toDateTime(1665053426)\n    AND type in (2,4)\n    and initial_user ='aiops'\n    and((positionCaseInsensitive(query,  'insert') = 1) or (positionCaseInsensitive(query,  'select') = 1))\nGROUP BY query\nORDER BY usage desc\nLIMIT 20",
     "round": "0s",
     "table": "query_log"
    },
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font><br />    <font color=\"navajowhite\">rand</font>() <font color=\"darkorange\">as</font> t,<br />    <font color=\"navajowhite\">substring</font>(query,  <font color=\"cornflowerblue\">1</font>,  <font color=\"cornflowerblue\">70</font>) <font color=\"darkorange\">AS</font> query,<br />    <font color=\"navajowhite\">avg</font>(memory_usage) usage,<br />    <font color=\"navajowhite\">count</font>() <font color=\"navajowhite\">count</font><br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br /><font color=\"darkorange\">WHERE</font><br />    <font color=\"darkcyan\">$timeFilter</font><br />    <font color=\"yellow\">AND</font> <font color=\"darkorange\">type</font> <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$type</font>)<br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br />    <font color=\"yellow\">and</font>(<font color=\"lightgreen\">'$query_type'</font> <font color=\"yellow\">=</font> <font color=\"lightgreen\">'all'</font> <font color=\"yellow\">or</font>(positionCaseInsensitive(query,  <font color=\"lightgreen\">'$query_type'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font>))<br /><font color=\"darkorange\">GROUP BY</font> query<br /><font color=\"darkorange\">ORDER BY</font> usage <font color=\"darkorange\">desc</font><br /><font color=\"darkorange\">LIMIT</font> <font color=\"darkcyan\">$top</font>",
     "query": "SELECT\n    query,\n    avg(memory_usage) usage,\n    count() count\nFROM system.query_log\nWHERE\n    $timeFilter\n    AND type in (2,4)\n    and initial_user ='aiops'\n    and((positionCaseInsensitive(query,  'insert') = 1) or (positionCaseInsensitive(query,  'select') = 1))\nGROUP BY query\nORDER BY usage desc\nLIMIT 20",
     "rawQuery": "SELECT\n    query,\n    avg(memory_usage) usage,\n    count() count\nFROM system.query_log\nWHERE\n    event_date >= toDate(1665049826) AND event_date <= toDate(1665053426) AND event_time >= toDateTime(1665049826) AND event_time <= toDateTime(1665053426)\n    AND type in (2,4)\n    and initial_user ='aiops'\n    and((positionCaseInsensitive(query,  'insert') = 1) or (positionCaseInsensitive(query,  'select') = 1))\nGROUP BY query\nORDER BY usage desc\nLIMIT 20",
     "round": "0s",
     "table": "query_log"
    },
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font><br />    <font color=\"navajowhite\">rand</font>() <font color=\"darkorange\">as</font> t,<br />    <font color=\"navajowhite\">substring</font>(query,  <font color=\"cornflowerblue\">1</font>,  <font color=\"cornflowerblue\">70</font>) <font color=\"darkorange\">AS</font> query,<br />    <font color=\"navajowhite\">avg</font>(memory_usage) usage,<br />    <font color=\"navajowhite\">count</font>() <font color=\"navajowhite\">count</font><br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br /><font color=\"darkorange\">WHERE</font><br />    <font color=\"darkcyan\">$timeFilter</font><br />    <font color=\"yellow\">AND</font> <font color=\"darkorange\">type</font> <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$type</font>)<br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br />    <font color=\"yellow\">and</font>(<font color=\"lightgreen\">'$query_type'</font> <font color=\"yellow\">=</font> <font color=\"lightgreen\">'all'</font> <font color=\"yellow\">or</font>(positionCaseInsensitive(query,  <font color=\"lightgreen\">'$query_type'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font>))<br /><font color=\"darkorange\">GROUP BY</font> query<br /><font color=\"darkorange\">ORDER BY</font> usage <font color=\"darkorange\">desc</font><br /><font color=\"darkorange\">LIMIT</font> <font color=\"darkcyan\">$top</font>",
     "query": "SELECT\n    query,\n    avg(memory_usage) usage,\n    count() count\nFROM system.query_log\nWHERE\n    $timeFilter\n    AND type in (2,4)\n    and initial_user ='aiops'\n    and((positionCaseInsensitive(query,  'insert') = 1) or (positionCaseInsensitive(query,  'select') = 1))\nGROUP BY query\nORDER BY usage desc\nLIMIT 20",
     "rawQuery": "SELECT\n    query,\n    avg(memory_usage) usage,\n    count() count\nFROM system.query_log\nWHERE\n    event_date >= toDate(1665049826) AND event_date <= toDate(1665053426) AND event_time >= toDateTime(1665049826) AND event_time <= toDateTime(1665053426)\n    AND type in (2,4)\n    and initial_user ='aiops'\n    and((positionCaseInsensitive(query,  'insert') = 1) or (positionCaseInsensitive(query,  'select') = 1))\nGROUP BY query\nORDER BY usage desc\nLIMIT 20",
     "round": "0s",
     "table": "query_log"
    },
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font><br />    <font color=\"navajowhite\">rand</font>() <font color=\"darkorange\">as</font> t,<br />    <font color=\"navajowhite\">substring</font>(query,  <font color=\"cornflowerblue\">1</font>,  <font color=\"cornflowerblue\">70</font>) <font color=\"darkorange\">AS</font> query,<br />    <font color=\"navajowhite\">avg</font>(memory_usage) usage,<br />    <font color=\"navajowhite\">count</font>() <font color=\"navajowhite\">count</font><br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br /><font color=\"darkorange\">WHERE</font><br />    <font color=\"darkcyan\">$timeFilter</font><br />    <font color=\"yellow\">AND</font> <font color=\"darkorange\">type</font> <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$type</font>)<br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br />    <font color=\"yellow\">and</font>(<font color=\"lightgreen\">'$query_type'</font> <font color=\"yellow\">=</font> <font color=\"lightgreen\">'all'</font> <font color=\"yellow\">or</font>(positionCaseInsensitive(query,  <font color=\"lightgreen\">'$query_type'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font>))<br /><font color=\"darkorange\">GROUP BY</font> query<br /><font color=\"darkorange\">ORDER BY</font> usage <font color=\"darkorange\">desc</font><br /><font color=\"darkorange\">LIMIT</font> <font color=\"darkcyan\">$top</font>",
     "query": "SELECT\n    query,\n    avg(memory_usage) usage,\n    count() count\nFROM system.query_log\nWHERE\n    $timeFilter\n    AND type in (2,4)\n    and initial_user ='aiops'\n    and((positionCaseInsensitive(query,  'insert') = 1) or (positionCaseInsensitive(query,  'select') = 1))\nGROUP BY query\nORDER BY usage desc\nLIMIT 20",
     "rawQuery": "SELECT\n    query,\n    avg(memory_usage) usage,\n    count() count\nFROM system.query_log\nWHERE\n    event_date >= toDate(1665049826) AND event_date <= toDate(1665053426) AND event_time >= toDateTime(1665049826) AND event_time <= toDateTime(1665053426)\n    AND type in (2,4)\n    and initial_user ='aiops'\n    and((positionCaseInsensitive(query,  'insert') = 1) or (positionCaseInsensitive(query,  'select') = 1))\nGROUP BY query\nORDER BY usage desc\nLIMIT 20",
     "round": "0s",
     "table": "query_log"
    }
   ]
  },
  {
   "title": "Insert duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font><br />    <font color=\"darkcyan\">$timeSeries</font> <font color=\"darkorange\">as</font> t,<br />    <font color=\"navajowhite\">avg</font>(query_duration_ms) insert_duration<br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br /><font color=\"darkorange\">WHERE</font><br />    <font color=\"darkcyan\">$timeFilter</font><br />    <font color=\"yellow\">AND</font> <font color=\"darkorange\">type</font> <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">2</font><br /><font color=\"yellow\">and</font> positionCaseInsensitive(query,  <font color=\"lightgreen\">'insert into'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font><br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br /><font color=\"darkorange\">GROUP BY</font> t<br /><font color=\"darkorange\">ORDER BY</font> t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(query_duration_ms) s1r1\nFROM system.query_log\nWHERE\n    $timeFilter\n    AND type = 2\nand positionCaseInsensitive(query,  'insert into') = 1\n    and initial_user ='aiops'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(event_time), 4) * 4) * 1000 as t,\n    avg(query_duration_ms) s1r1\nFROM system.query_log\nWHERE\n    event_date >= toDate(1664991899) AND event_date <= toDate(1664995499) AND event_time >= toDateTime(1664991899) AND event_time <= toDateTime(1664995499)\n    AND type = 2\nand positionCaseInsensitive(query,  'insert into') = 1\n    and initial_user ='aiops'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "query_log"
    },
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font><br />    <font color=\"darkcyan\">$timeSeries</font> <font color=\"darkorange\">as</font> t,<br />    <font color=\"navajowhite\">avg</font>(query_duration_ms) insert_duration<br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br /><font color=\"darkorange\">WHERE</font><br />    <font color=\"darkcyan\">$timeFilter</font><br />    <font color=\"yellow\">AND</font> <font color=\"darkorange\">type</font> <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">2</font><br /><font color=\"yellow\">and</font> positionCaseInsensitive(query,  <font color=\"lightgreen\">'insert into'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font><br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br /><font color=\"darkorange\">GROUP BY</font> t<br /><font color=\"darkorange\">ORDER BY</font> t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(query_duration_ms) s1r2\nFROM system.query_log\nWHERE\n    $timeFilter\n    AND type = 2\nand positionCaseInsensitive(query,  'insert into') = 1\n    and initial_user ='aiops'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(event_time), 4) * 4) * 1000 as t,\n    avg(query_duration_ms) s1r2\nFROM system.query_log\nWHERE\n    event_date >= toDate(1664991899) AND event_date <= toDate(1664995499) AND event_time >= toDateTime(1664991899) AND event_time <= toDateTime(1664995499)\n    AND type = 2\nand positionCaseInsensitive(query,  'insert into') = 1\n    and initial_user ='aiops'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "query_log"
    },
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font><br />    <font color=\"darkcyan\">$timeSeries</font> <font color=\"darkorange\">as</font> t,<br />    <font color=\"navajowhite\">avg</font>(query_duration_ms) insert_duration<br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br /><font color=\"darkorange\">WHERE</font><br />    <font color=\"darkcyan\">$timeFilter</font><br />    <font color=\"yellow\">AND</font> <font color=\"darkorange\">type</font> <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">2</font><br /><font color=\"yellow\">and</font> positionCaseInsensitive(query,  <font color=\"lightgreen\">'insert into'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font><br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br /><font color=\"darkorange\">GROUP BY</font> t<br /><font color=\"darkorange\">ORDER BY</font> t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(query_duration_ms) s2r1\nFROM system.query_log\nWHERE\n    $timeFilter\n    AND type = 2\nand positionCaseInsensitive(query,  'insert into') = 1\n    and initial_user ='aiops'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(event_time), 4) * 4) * 1000 as t,\n    avg(query_duration_ms) s2r1\nFROM system.query_log\nWHERE\n    event_date >= toDate(1664991899) AND event_date <= toDate(1664995499) AND event_time >= toDateTime(1664991899) AND event_time <= toDateTime(1664995499)\n    AND type = 2\nand positionCaseInsensitive(query,  'insert into') = 1\n    and initial_user ='aiops'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "query_log"
    },
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font><br />    <font color=\"darkcyan\">$timeSeries</font> <font color=\"darkorange\">as</font> t,<br />    <font color=\"navajowhite\">avg</font>(query_duration_ms) insert_duration<br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br /><font color=\"darkorange\">WHERE</font><br />    <font color=\"darkcyan\">$timeFilter</font><br />    <font color=\"yellow\">AND</font> <font color=\"darkorange\">type</font> <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">2</font><br /><font color=\"yellow\">and</font> positionCaseInsensitive(query,  <font color=\"lightgreen\">'insert into'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font><br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br /><font color=\"darkorange\">GROUP BY</font> t<br /><font color=\"darkorange\">ORDER BY</font> t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(query_duration_ms) s2r2\nFROM system.query_log\nWHERE\n    $timeFilter\n    AND type = 2\nand positionCaseInsensitive(query,  'insert into') = 1\n    and initial_user ='aiops'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(event_time), 4) * 4) * 1000 as t,\n    avg(query_duration_ms) s2r2\nFROM system.query_log\nWHERE\n    event_date >= toDate(1664991899) AND event_date <= toDate(1664995499) AND event_time >= toDateTime(1664991899) AND event_time <= toDateTime(1664995499)\n    AND type = 2\nand positionCaseInsensitive(query,  'insert into') = 1\n    and initial_user ='aiops'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "query_log"
    },
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font><br />    <font color=\"darkcyan\">$timeSeries</font> <font color=\"darkorange\">as</font> t,<br />    <font color=\"navajowhite\">avg</font>(query_duration_ms) insert_duration<br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br /><font color=\"darkorange\">WHERE</font><br />    <font color=\"darkcyan\">$timeFilter</font><br />    <font color=\"yellow\">AND</font> <font color=\"darkorange\">type</font> <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">2</font><br /><font color=\"yellow\">and</font> positionCaseInsensitive(query,  <font color=\"lightgreen\">'insert into'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font><br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br /><font color=\"darkorange\">GROUP BY</font> t<br /><font color=\"darkorange\">ORDER BY</font> t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(query_duration_ms) s3r1\nFROM system.query_log\nWHERE\n    $timeFilter\n    AND type = 2\nand positionCaseInsensitive(query,  'insert into') = 1\n    and initial_user ='aiops'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(event_time), 4) * 4) * 1000 as t,\n    avg(query_duration_ms) s3r1\nFROM system.query_log\nWHERE\n    event_date >= toDate(1664991899) AND event_date <= toDate(1664995499) AND event_time >= toDateTime(1664991899) AND event_time <= toDateTime(1664995499)\n    AND type = 2\nand positionCaseInsensitive(query,  'insert into') = 1\n    and initial_user ='aiops'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "query_log"
    },
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font><br />    <font color=\"darkcyan\">$timeSeries</font> <font color=\"darkorange\">as</font> t,<br />    <font color=\"navajowhite\">avg</font>(query_duration_ms) insert_duration<br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br /><font color=\"darkorange\">WHERE</font><br />    <font color=\"darkcyan\">$timeFilter</font><br />    <font color=\"yellow\">AND</font> <font color=\"darkorange\">type</font> <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">2</font><br /><font color=\"yellow\">and</font> positionCaseInsensitive(query,  <font color=\"lightgreen\">'insert into'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font><br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br /><font color=\"darkorange\">GROUP BY</font> t<br /><font color=\"darkorange\">ORDER BY</font> t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(query_duration_ms) s3r2\nFROM system.query_log\nWHERE\n    $timeFilter\n    AND type = 2\nand positionCaseInsensitive(query,  'insert into') = 1\n    and initial_user ='aiops'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(event_time), 4) * 4) * 1000 as t,\n    avg(query_duration_ms) s3r2\nFROM system.query_log\nWHERE\n    event_date >= toDate(1664991899) AND event_date <= toDate(1664995499) AND event_time >= toDateTime(1664991899) AND event_time <= toDateTime(1664995499)\n    AND type = 2\nand positionCaseInsensitive(query,  'insert into') = 1\n    and initial_user ='aiops'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "query_log"
    },
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font><br />    <font color=\"darkcyan\">$timeSeries</font> <font color=\"darkorange\">as</font> t,<br />    <font color=\"navajowhite\">avg</font>(query_duration_ms) insert_duration<br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br /><font color=\"darkorange\">WHERE</font><br />    <font color=\"darkcyan\">$timeFilter</font><br />    <font color=\"yellow\">AND</font> <font color=\"darkorange\">type</font> <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">2</font><br /><font color=\"yellow\">and</font> positionCaseInsensitive(query,  <font color=\"lightgreen\">'insert into'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font><br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br /><font color=\"darkorange\">GROUP BY</font> t<br /><font color=\"darkorange\">ORDER BY</font> t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(query_duration_ms) s4r1\nFROM system.query_log\nWHERE\n    $timeFilter\n    AND type = 2\nand positionCaseInsensitive(query,  'insert into') = 1\n    and initial_user ='aiops'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(event_time), 4) * 4) * 1000 as t,\n    avg(query_duration_ms) s4r1\nFROM system.query_log\nWHERE\n    event_date >= toDate(1664991899) AND event_date <= toDate(1664995499) AND event_time >= toDateTime(1664991899) AND event_time <= toDateTime(1664995499)\n    AND type = 2\nand positionCaseInsensitive(query,  'insert into') = 1\n    and initial_user ='aiops'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "query_log"
    },
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font><br />    <font color=\"darkcyan\">$timeSeries</font> <font color=\"darkorange\">as</font> t,<br />    <font color=\"navajowhite\">avg</font>(query_duration_ms) insert_duration<br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br /><font color=\"darkorange\">WHERE</font><br />    <font color=\"darkcyan\">$timeFilter</font><br />    <font color=\"yellow\">AND</font> <font color=\"darkorange\">type</font> <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">2</font><br /><font color=\"yellow\">and</font> positionCaseInsensitive(query,  <font color=\"lightgreen\">'insert into'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font><br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br /><font color=\"darkorange\">GROUP BY</font> t<br /><font color=\"darkorange\">ORDER BY</font> t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(query_duration_ms) s4r2\nFROM system.query_log\nWHERE\n    $timeFilter\n    AND type = 2\nand positionCaseInsensitive(query,  'insert into') = 1\n    and initial_user ='aiops'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(event_time), 4) * 4) * 1000 as t,\n    avg(query_duration_ms) s4r2\nFROM system.query_log\nWHERE\n    event_date >= toDate(1664991899) AND event_date <= toDate(1664995499) AND event_time >= toDateTime(1664991899) AND event_time <= toDateTime(1664995499)\n    AND type = 2\nand positionCaseInsensitive(query,  'insert into') = 1\n    and initial_user ='aiops'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "query_log"
    },
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font><br />    <font color=\"darkcyan\">$timeSeries</font> <font color=\"darkorange\">as</font> t,<br />    <font color=\"navajowhite\">avg</font>(query_duration_ms) insert_duration<br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br /><font color=\"darkorange\">WHERE</font><br />    <font color=\"darkcyan\">$timeFilter</font><br />    <font color=\"yellow\">AND</font> <font color=\"darkorange\">type</font> <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">2</font><br /><font color=\"yellow\">and</font> positionCaseInsensitive(query,  <font color=\"lightgreen\">'insert into'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font><br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br /><font color=\"darkorange\">GROUP BY</font> t<br /><font color=\"darkorange\">ORDER BY</font> t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(query_duration_ms) s5r1\nFROM system.query_log\nWHERE\n    $timeFilter\n    AND type = 2\nand positionCaseInsensitive(query,  'insert into') = 1\n    and initial_user ='aiops'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(event_time), 4) * 4) * 1000 as t,\n    avg(query_duration_ms) s5r1\nFROM system.query_log\nWHERE\n    event_date >= toDate(1664991899) AND event_date <= toDate(1664995499) AND event_time >= toDateTime(1664991899) AND event_time <= toDateTime(1664995499)\n    AND type = 2\nand positionCaseInsensitive(query,  'insert into') = 1\n    and initial_user ='aiops'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "query_log"
    },
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font><br />    <font color=\"darkcyan\">$timeSeries</font> <font color=\"darkorange\">as</font> t,<br />    <font color=\"navajowhite\">avg</font>(query_duration_ms) insert_duration<br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br /><font color=\"darkorange\">WHERE</font><br />    <font color=\"darkcyan\">$timeFilter</font><br />    <font color=\"yellow\">AND</font> <font color=\"darkorange\">type</font> <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">2</font><br /><font color=\"yellow\">and</font> positionCaseInsensitive(query,  <font color=\"lightgreen\">'insert into'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font><br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br /><font color=\"darkorange\">GROUP BY</font> t<br /><font color=\"darkorange\">ORDER BY</font> t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(query_duration_ms) s5r2\nFROM system.query_log\nWHERE\n    $timeFilter\n    AND type = 2\nand positionCaseInsensitive(query,  'insert into') = 1\n    and initial_user ='aiops'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(event_time), 4) * 4) * 1000 as t,\n    avg(query_duration_ms) s5r2\nFROM system.query_log\nWHERE\n    event_date >= toDate(1664991899) AND event_date <= toDate(1664995499) AND event_time >= toDateTime(1664991899) AND event_time <= toDateTime(1664995499)\n    AND type = 2\nand positionCaseInsensitive(query,  'insert into') = 1\n    and initial_user ='aiops'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "query_log"
    }
   ]
  },
  {
   "title": "Select duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font><br />    <font color=\"darkcyan\">$timeSeries</font> <font color=\"darkorange\">as</font> t,<br />    <font color=\"navajowhite\">avg</font>(query_duration_ms) insert_duration<br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br /><font color=\"darkorange\">WHERE</font><br />    <font color=\"darkcyan\">$timeFilter</font><br />    <font color=\"yellow\">AND</font> <font color=\"darkorange\">type</font> <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">2</font><br /><font color=\"yellow\">and</font> positionCaseInsensitive(query,  <font color=\"lightgreen\">'insert into'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font><br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br /><font color=\"darkorange\">GROUP BY</font> t<br /><font color=\"darkorange\">ORDER BY</font> t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(query_duration_ms) s1r1\nFROM system.query_log\nWHERE\n    $timeFilter\n    AND type = 2\nand positionCaseInsensitive(query,  'select') = 1\n    and initial_user ='aiops'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(event_time), 4) * 4) * 1000 as t,\n    avg(query_duration_ms) s1r1\nFROM system.query_log\nWHERE\n    event_date >= toDate(1664992001) AND event_date <= toDate(1664995601) AND event_time >= toDateTime(1664992001) AND event_time <= toDateTime(1664995601)\n    AND type = 2\nand positionCaseInsensitive(query,  'select') = 1\n    and initial_user ='aiops'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "query_log"
    },
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font><br />    <font color=\"darkcyan\">$timeSeries</font> <font color=\"darkorange\">as</font> t,<br />    <font color=\"navajowhite\">avg</font>(query_duration_ms) insert_duration<br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br /><font color=\"darkorange\">WHERE</font><br />    <font color=\"darkcyan\">$timeFilter</font><br />    <font color=\"yellow\">AND</font> <font color=\"darkorange\">type</font> <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">2</font><br /><font color=\"yellow\">and</font> positionCaseInsensitive(query,  <font color=\"lightgreen\">'insert into'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font><br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br /><font color=\"darkorange\">GROUP BY</font> t<br /><font color=\"darkorange\">ORDER BY</font> t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(query_duration_ms) s1r2\nFROM system.query_log\nWHERE\n    $timeFilter\n    AND type = 2\nand positionCaseInsensitive(query,  'select') = 1\n    and initial_user ='aiops'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(event_time), 4) * 4) * 1000 as t,\n    avg(query_duration_ms) s1r2\nFROM system.query_log\nWHERE\n    event_date >= toDate(1664992001) AND event_date <= toDate(1664995601) AND event_time >= toDateTime(1664992001) AND event_time <= toDateTime(1664995601)\n    AND type = 2\nand positionCaseInsensitive(query,  'select') = 1\n    and initial_user ='aiops'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "query_log"
    },
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font><br />    <font color=\"darkcyan\">$timeSeries</font> <font color=\"darkorange\">as</font> t,<br />    <font color=\"navajowhite\">avg</font>(query_duration_ms) insert_duration<br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br /><font color=\"darkorange\">WHERE</font><br />    <font color=\"darkcyan\">$timeFilter</font><br />    <font color=\"yellow\">AND</font> <font color=\"darkorange\">type</font> <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">2</font><br /><font color=\"yellow\">and</font> positionCaseInsensitive(query,  <font color=\"lightgreen\">'insert into'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font><br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br /><font color=\"darkorange\">GROUP BY</font> t<br /><font color=\"darkorange\">ORDER BY</font> t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(query_duration_ms) s2r1\nFROM system.query_log\nWHERE\n    $timeFilter\n    AND type = 2\nand positionCaseInsensitive(query,  'select') = 1\n    and initial_user ='aiops'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(event_time), 4) * 4) * 1000 as t,\n    avg(query_duration_ms) s2r1\nFROM system.query_log\nWHERE\n    event_date >= toDate(1664992001) AND event_date <= toDate(1664995601) AND event_time >= toDateTime(1664992001) AND event_time <= toDateTime(1664995601)\n    AND type = 2\nand positionCaseInsensitive(query,  'select') = 1\n    and initial_user ='aiops'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "query_log"
    },
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font><br />    <font color=\"darkcyan\">$timeSeries</font> <font color=\"darkorange\">as</font> t,<br />    <font color=\"navajowhite\">avg</font>(query_duration_ms) insert_duration<br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br /><font color=\"darkorange\">WHERE</font><br />    <font color=\"darkcyan\">$timeFilter</font><br />    <font color=\"yellow\">AND</font> <font color=\"darkorange\">type</font> <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">2</font><br /><font color=\"yellow\">and</font> positionCaseInsensitive(query,  <font color=\"lightgreen\">'insert into'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font><br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br /><font color=\"darkorange\">GROUP BY</font> t<br /><font color=\"darkorange\">ORDER BY</font> t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(query_duration_ms) s2r2\nFROM system.query_log\nWHERE\n    $timeFilter\n    AND type = 2\nand positionCaseInsensitive(query,  'select') = 1\n    and initial_user ='aiops'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(event_time), 4) * 4) * 1000 as t,\n    avg(query_duration_ms) s2r2\nFROM system.query_log\nWHERE\n    event_date >= toDate(1664992001) AND event_date <= toDate(1664995601) AND event_time >= toDateTime(1664992001) AND event_time <= toDateTime(1664995601)\n    AND type = 2\nand positionCaseInsensitive(query,  'select') = 1\n    and initial_user ='aiops'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "query_log"
    },
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font><br />    <font color=\"darkcyan\">$timeSeries</font> <font color=\"darkorange\">as</font> t,<br />    <font color=\"navajowhite\">avg</font>(query_duration_ms) insert_duration<br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br /><font color=\"darkorange\">WHERE</font><br />    <font color=\"darkcyan\">$timeFilter</font><br />    <font color=\"yellow\">AND</font> <font color=\"darkorange\">type</font> <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">2</font><br /><font color=\"yellow\">and</font> positionCaseInsensitive(query,  <font color=\"lightgreen\">'insert into'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font><br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br /><font color=\"darkorange\">GROUP BY</font> t<br /><font color=\"darkorange\">ORDER BY</font> t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(query_duration_ms) s3r1\nFROM system.query_log\nWHERE\n    $timeFilter\n    AND type = 2\nand positionCaseInsensitive(query,  'select') = 1\n    and initial_user ='aiops'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(event_time), 4) * 4) * 1000 as t,\n    avg(query_duration_ms) s3r1\nFROM system.query_log\nWHERE\n    event_date >= toDate(1664992001) AND event_date <= toDate(1664995601) AND event_time >= toDateTime(1664992001) AND event_time <= toDateTime(1664995601)\n    AND type = 2\nand positionCaseInsensitive(query,  'select') = 1\n    and initial_user ='aiops'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "query_log"
    },
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font><br />    <font color=\"darkcyan\">$timeSeries</font> <font color=\"darkorange\">as</font> t,<br />    <font color=\"navajowhite\">avg</font>(query_duration_ms) insert_duration<br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br /><font color=\"darkorange\">WHERE</font><br />    <font color=\"darkcyan\">$timeFilter</font><br />    <font color=\"yellow\">AND</font> <font color=\"darkorange\">type</font> <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">2</font><br /><font color=\"yellow\">and</font> positionCaseInsensitive(query,  <font color=\"lightgreen\">'insert into'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font><br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br /><font color=\"darkorange\">GROUP BY</font> t<br /><font color=\"darkorange\">ORDER BY</font> t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(query_duration_ms) s3r2\nFROM system.query_log\nWHERE\n    $timeFilter\n    AND type = 2\nand positionCaseInsensitive(query,  'select') = 1\n    and initial_user ='aiops'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(event_time), 4) * 4) * 1000 as t,\n    avg(query_duration_ms) s3r2\nFROM system.query_log\nWHERE\n    event_date >= toDate(1664992001) AND event_date <= toDate(1664995601) AND event_time >= toDateTime(1664992001) AND event_time <= toDateTime(1664995601)\n    AND type = 2\nand positionCaseInsensitive(query,  'select') = 1\n    and initial_user ='aiops'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "query_log"
    },
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font><br />    <font color=\"darkcyan\">$timeSeries</font> <font color=\"darkorange\">as</font> t,<br />    <font color=\"navajowhite\">avg</font>(query_duration_ms) insert_duration<br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br /><font color=\"darkorange\">WHERE</font><br />    <font color=\"darkcyan\">$timeFilter</font><br />    <font color=\"yellow\">AND</font> <font color=\"darkorange\">type</font> <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">2</font><br /><font color=\"yellow\">and</font> positionCaseInsensitive(query,  <font color=\"lightgreen\">'insert into'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font><br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br /><font color=\"darkorange\">GROUP BY</font> t<br /><font color=\"darkorange\">ORDER BY</font> t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(query_duration_ms) s4r1\nFROM system.query_log\nWHERE\n    $timeFilter\n    AND type = 2\nand positionCaseInsensitive(query,  'select') = 1\n    and initial_user ='aiops'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(event_time), 4) * 4) * 1000 as t,\n    avg(query_duration_ms) s4r1\nFROM system.query_log\nWHERE\n    event_date >= toDate(1664992001) AND event_date <= toDate(1664995601) AND event_time >= toDateTime(1664992001) AND event_time <= toDateTime(1664995601)\n    AND type = 2\nand positionCaseInsensitive(query,  'select') = 1\n    and initial_user ='aiops'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "query_log"
    },
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font><br />    <font color=\"darkcyan\">$timeSeries</font> <font color=\"darkorange\">as</font> t,<br />    <font color=\"navajowhite\">avg</font>(query_duration_ms) insert_duration<br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br /><font color=\"darkorange\">WHERE</font><br />    <font color=\"darkcyan\">$timeFilter</font><br />    <font color=\"yellow\">AND</font> <font color=\"darkorange\">type</font> <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">2</font><br /><font color=\"yellow\">and</font> positionCaseInsensitive(query,  <font color=\"lightgreen\">'insert into'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font><br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br /><font color=\"darkorange\">GROUP BY</font> t<br /><font color=\"darkorange\">ORDER BY</font> t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(query_duration_ms) s4r2\nFROM system.query_log\nWHERE\n    $timeFilter\n    AND type = 2\nand positionCaseInsensitive(query,  'select') = 1\n    and initial_user ='aiops'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(event_time), 4) * 4) * 1000 as t,\n    avg(query_duration_ms) s4r2\nFROM system.query_log\nWHERE\n    event_date >= toDate(1664992001) AND event_date <= toDate(1664995601) AND event_time >= toDateTime(1664992001) AND event_time <= toDateTime(1664995601)\n    AND type = 2\nand positionCaseInsensitive(query,  'select') = 1\n    and initial_user ='aiops'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "query_log"
    },
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font><br />    <font color=\"darkcyan\">$timeSeries</font> <font color=\"darkorange\">as</font> t,<br />    <font color=\"navajowhite\">avg</font>(query_duration_ms) insert_duration<br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br /><font color=\"darkorange\">WHERE</font><br />    <font color=\"darkcyan\">$timeFilter</font><br />    <font color=\"yellow\">AND</font> <font color=\"darkorange\">type</font> <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">2</font><br /><font color=\"yellow\">and</font> positionCaseInsensitive(query,  <font color=\"lightgreen\">'insert into'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font><br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br /><font color=\"darkorange\">GROUP BY</font> t<br /><font color=\"darkorange\">ORDER BY</font> t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(query_duration_ms) s5r1\nFROM system.query_log\nWHERE\n    $timeFilter\n    AND type = 2\nand positionCaseInsensitive(query,  'select') = 1\n    and initial_user ='aiops'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(event_time), 4) * 4) * 1000 as t,\n    avg(query_duration_ms) s5r1\nFROM system.query_log\nWHERE\n    event_date >= toDate(1664992001) AND event_date <= toDate(1664995601) AND event_time >= toDateTime(1664992001) AND event_time <= toDateTime(1664995601)\n    AND type = 2\nand positionCaseInsensitive(query,  'select') = 1\n    and initial_user ='aiops'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "query_log"
    },
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font><br />    <font color=\"darkcyan\">$timeSeries</font> <font color=\"darkorange\">as</font> t,<br />    <font color=\"navajowhite\">avg</font>(query_duration_ms) insert_duration<br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br /><font color=\"darkorange\">WHERE</font><br />    <font color=\"darkcyan\">$timeFilter</font><br />    <font color=\"yellow\">AND</font> <font color=\"darkorange\">type</font> <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">2</font><br /><font color=\"yellow\">and</font> positionCaseInsensitive(query,  <font color=\"lightgreen\">'insert into'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font><br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br /><font color=\"darkorange\">GROUP BY</font> t<br /><font color=\"darkorange\">ORDER BY</font> t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(query_duration_ms) s5r2\nFROM system.query_log\nWHERE\n    $timeFilter\n    AND type = 2\nand positionCaseInsensitive(query,  'select') = 1\n    and initial_user ='aiops'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(event_time), 4) * 4) * 1000 as t,\n    avg(query_duration_ms) s5r2\nFROM system.query_log\nWHERE\n    event_date >= toDate(1664992001) AND event_date <= toDate(1664995601) AND event_time >= toDateTime(1664992001) AND event_time <= toDateTime(1664995601)\n    AND type = 2\nand positionCaseInsensitive(query,  'select') = 1\n    and initial_user ='aiops'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "query_log"
    }
   ]
  },
  {
   "title": "Query logs",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font><br />    event_time,<br />    user,<br />    query_duration_ms duration,<br />    memory_usage memory,<br />    if(exception<font color=\"yellow\">!=</font><font color=\"lightgreen\">''</font>, <font color=\"lightgreen\">'fail'</font>, <font color=\"lightgreen\">'success'</font>) result,<br />    <font color=\"navajowhite\">concat</font>(<font color=\"navajowhite\">substring</font>(query,<font color=\"cornflowerblue\">1</font>,<font color=\"cornflowerblue\">120</font>), <font color=\"lightgreen\">'...'</font>) query<br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br /><font color=\"darkorange\">WHERE</font> <font color=\"darkcyan\">$timeFilter</font><br />    <font color=\"yellow\">AND</font> <font color=\"darkorange\">type</font> <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$type</font>)<br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br />    <font color=\"yellow\">and</font>(<font color=\"lightgreen\">'$query_type'</font> <font color=\"yellow\">=</font> <font color=\"lightgreen\">'all'</font> <font color=\"yellow\">or</font>(positionCaseInsensitive(query,  <font color=\"lightgreen\">'$query_type'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font>))<br /><font color=\"darkorange\">ORDER BY</font> event_time <font color=\"darkorange\">DESC</font><br /><font color=\"darkorange\">LIMIT</font> <font color=\"cornflowerblue\">1000</font>",
     "query": "SELECT\n    event_time,\n    user,\n    query_duration_ms duration,\n    memory_usage memory,\n    if(exception!='', 'fail', 'success') result,\n    query\nFROM system.query_log\nWHERE $timeFilter\n    AND type in (1,2,3,4)\n    and initial_user ='aiops'\n    and((positionCaseInsensitive(query,  'insert into') = 1) or (positionCaseInsensitive(query,  'select') = 1))\nORDER BY event_time DESC\nLIMIT 100",
     "rawQuery": "SELECT\n    event_time,\n    user,\n    query_duration_ms duration,\n    memory_usage memory,\n    if(exception!='', 'fail', 'success') result,\n    query\nFROM system.query_log\nWHERE event_date >= toDate(1665049851) AND event_date <= toDate(1665053451) AND event_time >= toDateTime(1665049851) AND event_time <= toDateTime(1665053451)\n    AND type in (1,2,3,4)\n    and initial_user ='aiops'\n    and((positionCaseInsensitive(query,  'insert into') = 1) or (positionCaseInsensitive(query,  'select') = 1))\nORDER BY event_time DESC\nLIMIT 100",
     "round": "0s",
     "table": "query_log"
    },
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font><br />    event_time,<br />    user,<br />    query_duration_ms duration,<br />    memory_usage memory,<br />    if(exception<font color=\"yellow\">!=</font><font color=\"lightgreen\">''</font>, <font color=\"lightgreen\">'fail'</font>, <font color=\"lightgreen\">'success'</font>) result,<br />    <font color=\"navajowhite\">concat</font>(<font color=\"navajowhite\">substring</font>(query,<font color=\"cornflowerblue\">1</font>,<font color=\"cornflowerblue\">120</font>), <font color=\"lightgreen\">'...'</font>) query<br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br /><font color=\"darkorange\">WHERE</font> <font color=\"darkcyan\">$timeFilter</font><br />    <font color=\"yellow\">AND</font> <font color=\"darkorange\">type</font> <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$type</font>)<br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br />    <font color=\"yellow\">and</font>(<font color=\"lightgreen\">'$query_type'</font> <font color=\"yellow\">=</font> <font color=\"lightgreen\">'all'</font> <font color=\"yellow\">or</font>(positionCaseInsensitive(query,  <font color=\"lightgreen\">'$query_type'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font>))<br /><font color=\"darkorange\">ORDER BY</font> event_time <font color=\"darkorange\">DESC</font><br /><font color=\"darkorange\">LIMIT</font> <font color=\"cornflowerblue\">1000</font>",
     "query": "SELECT\n    event_time,\n    user,\n    query_duration_ms duration,\n    memory_usage memory,\n    if(exception!='', 'fail', 'success') result,\n    query\nFROM system.query_log\nWHERE $timeFilter\n    AND type in (1,2,3,4)\n    and initial_user ='aiops'\n    and((positionCaseInsensitive(query,  'insert into') = 1) or (positionCaseInsensitive(query,  'select') = 1))\nORDER BY event_time DESC\nLIMIT 100",
     "rawQuery": "SELECT\n    event_time,\n    user,\n    query_duration_ms duration,\n    memory_usage memory,\n    if(exception!='', 'fail', 'success') result,\n    query\nFROM system.query_log\nWHERE event_date >= toDate(1665049851) AND event_date <= toDate(1665053451) AND event_time >= toDateTime(1665049851) AND event_time <= toDateTime(1665053451)\n    AND type in (1,2,3,4)\n    and initial_user ='aiops'\n    and((positionCaseInsensitive(query,  'insert into') = 1) or (positionCaseInsensitive(query,  'select') = 1))\nORDER BY event_time DESC\nLIMIT 100",
     "round": "0s",
     "table": "query_log"
    },
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font><br />    event_time,<br />    user,<br />    query_duration_ms duration,<br />    memory_usage memory,<br />    if(exception<font color=\"yellow\">!=</font><font color=\"lightgreen\">''</font>, <font color=\"lightgreen\">'fail'</font>, <font color=\"lightgreen\">'success'</font>) result,<br />    <font color=\"navajowhite\">concat</font>(<font color=\"navajowhite\">substring</font>(query,<font color=\"cornflowerblue\">1</font>,<font color=\"cornflowerblue\">120</font>), <font color=\"lightgreen\">'...'</font>) query<br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br /><font color=\"darkorange\">WHERE</font> <font color=\"darkcyan\">$timeFilter</font><br />    <font color=\"yellow\">AND</font> <font color=\"darkorange\">type</font> <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$type</font>)<br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br />    <font color=\"yellow\">and</font>(<font color=\"lightgreen\">'$query_type'</font> <font color=\"yellow\">=</font> <font color=\"lightgreen\">'all'</font> <font color=\"yellow\">or</font>(positionCaseInsensitive(query,  <font color=\"lightgreen\">'$query_type'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font>))<br /><font color=\"darkorange\">ORDER BY</font> event_time <font color=\"darkorange\">DESC</font><br /><font color=\"darkorange\">LIMIT</font> <font color=\"cornflowerblue\">1000</font>",
     "query": "SELECT\n    event_time,\n    user,\n    query_duration_ms duration,\n    memory_usage memory,\n    if(exception!='', 'fail', 'success') result,\n    query\nFROM system.query_log\nWHERE $timeFilter\n    AND type in (1,2,3,4)\n    and initial_user ='aiops'\n    and((positionCaseInsensitive(query,  'insert into') = 1) or (positionCaseInsensitive(query,  'select') = 1))\nORDER BY event_time DESC\nLIMIT 100",
     "rawQuery": "SELECT\n    event_time,\n    user,\n    query_duration_ms duration,\n    memory_usage memory,\n    if(exception!='', 'fail', 'success') result,\n    query\nFROM system.query_log\nWHERE event_date >= toDate(1665049851) AND event_date <= toDate(1665053451) AND event_time >= toDateTime(1665049851) AND event_time <= toDateTime(1665053451)\n    AND type in (1,2,3,4)\n    and initial_user ='aiops'\n    and((positionCaseInsensitive(query,  'insert into') = 1) or (positionCaseInsensitive(query,  'select') = 1))\nORDER BY event_time DESC\nLIMIT 100",
     "round": "0s",
     "table": "query_log"
    },
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font><br />    event_time,<br />    user,<br />    query_duration_ms duration,<br />    memory_usage memory,<br />    if(exception<font color=\"yellow\">!=</font><font color=\"lightgreen\">''</font>, <font color=\"lightgreen\">'fail'</font>, <font color=\"lightgreen\">'success'</font>) result,<br />    <font color=\"navajowhite\">concat</font>(<font color=\"navajowhite\">substring</font>(query,<font color=\"cornflowerblue\">1</font>,<font color=\"cornflowerblue\">120</font>), <font color=\"lightgreen\">'...'</font>) query<br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br /><font color=\"darkorange\">WHERE</font> <font color=\"darkcyan\">$timeFilter</font><br />    <font color=\"yellow\">AND</font> <font color=\"darkorange\">type</font> <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$type</font>)<br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br />    <font color=\"yellow\">and</font>(<font color=\"lightgreen\">'$query_type'</font> <font color=\"yellow\">=</font> <font color=\"lightgreen\">'all'</font> <font color=\"yellow\">or</font>(positionCaseInsensitive(query,  <font color=\"lightgreen\">'$query_type'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font>))<br /><font color=\"darkorange\">ORDER BY</font> event_time <font color=\"darkorange\">DESC</font><br /><font color=\"darkorange\">LIMIT</font> <font color=\"cornflowerblue\">1000</font>",
     "query": "SELECT\n    event_time,\n    user,\n    query_duration_ms duration,\n    memory_usage memory,\n    if(exception!='', 'fail', 'success') result,\n    query\nFROM system.query_log\nWHERE $timeFilter\n    AND type in (1,2,3,4)\n    and initial_user ='aiops'\n    and((positionCaseInsensitive(query,  'insert into') = 1) or (positionCaseInsensitive(query,  'select') = 1))\nORDER BY event_time DESC\nLIMIT 100",
     "rawQuery": "SELECT\n    event_time,\n    user,\n    query_duration_ms duration,\n    memory_usage memory,\n    if(exception!='', 'fail', 'success') result,\n    query\nFROM system.query_log\nWHERE event_date >= toDate(1665049851) AND event_date <= toDate(1665053451) AND event_time >= toDateTime(1665049851) AND event_time <= toDateTime(1665053451)\n    AND type in (1,2,3,4)\n    and initial_user ='aiops'\n    and((positionCaseInsensitive(query,  'insert into') = 1) or (positionCaseInsensitive(query,  'select') = 1))\nORDER BY event_time DESC\nLIMIT 100",
     "round": "0s",
     "table": "query_log"
    },
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font><br />    event_time,<br />    user,<br />    query_duration_ms duration,<br />    memory_usage memory,<br />    if(exception<font color=\"yellow\">!=</font><font color=\"lightgreen\">''</font>, <font color=\"lightgreen\">'fail'</font>, <font color=\"lightgreen\">'success'</font>) result,<br />    <font color=\"navajowhite\">concat</font>(<font color=\"navajowhite\">substring</font>(query,<font color=\"cornflowerblue\">1</font>,<font color=\"cornflowerblue\">120</font>), <font color=\"lightgreen\">'...'</font>) query<br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br /><font color=\"darkorange\">WHERE</font> <font color=\"darkcyan\">$timeFilter</font><br />    <font color=\"yellow\">AND</font> <font color=\"darkorange\">type</font> <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$type</font>)<br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br />    <font color=\"yellow\">and</font>(<font color=\"lightgreen\">'$query_type'</font> <font color=\"yellow\">=</font> <font color=\"lightgreen\">'all'</font> <font color=\"yellow\">or</font>(positionCaseInsensitive(query,  <font color=\"lightgreen\">'$query_type'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font>))<br /><font color=\"darkorange\">ORDER BY</font> event_time <font color=\"darkorange\">DESC</font><br /><font color=\"darkorange\">LIMIT</font> <font color=\"cornflowerblue\">1000</font>",
     "query": "SELECT\n    event_time,\n    user,\n    query_duration_ms duration,\n    memory_usage memory,\n    if(exception!='', 'fail', 'success') result,\n    query\nFROM system.query_log\nWHERE $timeFilter\n    AND type in (1,2,3,4)\n    and initial_user ='aiops'\n    and((positionCaseInsensitive(query,  'insert into') = 1) or (positionCaseInsensitive(query,  'select') = 1))\nORDER BY event_time DESC\nLIMIT 100",
     "rawQuery": "SELECT\n    event_time,\n    user,\n    query_duration_ms duration,\n    memory_usage memory,\n    if(exception!='', 'fail', 'success') result,\n    query\nFROM system.query_log\nWHERE event_date >= toDate(1665049851) AND event_date <= toDate(1665053451) AND event_time >= toDateTime(1665049851) AND event_time <= toDateTime(1665053451)\n    AND type in (1,2,3,4)\n    and initial_user ='aiops'\n    and((positionCaseInsensitive(query,  'insert into') = 1) or (positionCaseInsensitive(query,  'select') = 1))\nORDER BY event_time DESC\nLIMIT 100",
     "round": "0s",
     "table": "query_log"
    },
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font><br />    event_time,<br />    user,<br />    query_duration_ms duration,<br />    memory_usage memory,<br />    if(exception<font color=\"yellow\">!=</font><font color=\"lightgreen\">''</font>, <font color=\"lightgreen\">'fail'</font>, <font color=\"lightgreen\">'success'</font>) result,<br />    <font color=\"navajowhite\">concat</font>(<font color=\"navajowhite\">substring</font>(query,<font color=\"cornflowerblue\">1</font>,<font color=\"cornflowerblue\">120</font>), <font color=\"lightgreen\">'...'</font>) query<br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br /><font color=\"darkorange\">WHERE</font> <font color=\"darkcyan\">$timeFilter</font><br />    <font color=\"yellow\">AND</font> <font color=\"darkorange\">type</font> <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$type</font>)<br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br />    <font color=\"yellow\">and</font>(<font color=\"lightgreen\">'$query_type'</font> <font color=\"yellow\">=</font> <font color=\"lightgreen\">'all'</font> <font color=\"yellow\">or</font>(positionCaseInsensitive(query,  <font color=\"lightgreen\">'$query_type'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font>))<br /><font color=\"darkorange\">ORDER BY</font> event_time <font color=\"darkorange\">DESC</font><br /><font color=\"darkorange\">LIMIT</font> <font color=\"cornflowerblue\">1000</font>",
     "query": "SELECT\n    event_time,\n    user,\n    query_duration_ms duration,\n    memory_usage memory,\n    if(exception!='', 'fail', 'success') result,\n    query\nFROM system.query_log\nWHERE $timeFilter\n    AND type in (1,2,3,4)\n    and initial_user ='aiops'\n    and((positionCaseInsensitive(query,  'insert into') = 1) or (positionCaseInsensitive(query,  'select') = 1))\nORDER BY event_time DESC\nLIMIT 100",
     "rawQuery": "SELECT\n    event_time,\n    user,\n    query_duration_ms duration,\n    memory_usage memory,\n    if(exception!='', 'fail', 'success') result,\n    query\nFROM system.query_log\nWHERE event_date >= toDate(1665049851) AND event_date <= toDate(1665053451) AND event_time >= toDateTime(1665049851) AND event_time <= toDateTime(1665053451)\n    AND type in (1,2,3,4)\n    and initial_user ='aiops'\n    and((positionCaseInsensitive(query,  'insert into') = 1) or (positionCaseInsensitive(query,  'select') = 1))\nORDER BY event_time DESC\nLIMIT 100",
     "round": "0s",
     "table": "query_log"
    },
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font><br />    event_time,<br />    user,<br />    query_duration_ms duration,<br />    memory_usage memory,<br />    if(exception<font color=\"yellow\">!=</font><font color=\"lightgreen\">''</font>, <font color=\"lightgreen\">'fail'</font>, <font color=\"lightgreen\">'success'</font>) result,<br />    <font color=\"navajowhite\">concat</font>(<font color=\"navajowhite\">substring</font>(query,<font color=\"cornflowerblue\">1</font>,<font color=\"cornflowerblue\">120</font>), <font color=\"lightgreen\">'...'</font>) query<br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br /><font color=\"darkorange\">WHERE</font> <font color=\"darkcyan\">$timeFilter</font><br />    <font color=\"yellow\">AND</font> <font color=\"darkorange\">type</font> <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$type</font>)<br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br />    <font color=\"yellow\">and</font>(<font color=\"lightgreen\">'$query_type'</font> <font color=\"yellow\">=</font> <font color=\"lightgreen\">'all'</font> <font color=\"yellow\">or</font>(positionCaseInsensitive(query,  <font color=\"lightgreen\">'$query_type'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font>))<br /><font color=\"darkorange\">ORDER BY</font> event_time <font color=\"darkorange\">DESC</font><br /><font color=\"darkorange\">LIMIT</font> <font color=\"cornflowerblue\">1000</font>",
     "query": "SELECT\n    event_time,\n    user,\n    query_duration_ms duration,\n    memory_usage memory,\n    if(exception!='', 'fail', 'success') result,\n    query\nFROM system.query_log\nWHERE $timeFilter\n    AND type in (1,2,3,4)\n    and initial_user ='aiops'\n    and((positionCaseInsensitive(query,  'insert into') = 1) or (positionCaseInsensitive(query,  'select') = 1))\nORDER BY event_time DESC\nLIMIT 100",
     "rawQuery": "SELECT\n    event_time,\n    user,\n    query_duration_ms duration,\n    memory_usage memory,\n    if(exception!='', 'fail', 'success') result,\n    query\nFROM system.query_log\nWHERE event_date >= toDate(1665049851) AND event_date <= toDate(1665053451) AND event_time >= toDateTime(1665049851) AND event_time <= toDateTime(1665053451)\n    AND type in (1,2,3,4)\n    and initial_user ='aiops'\n    and((positionCaseInsensitive(query,  'insert into') = 1) or (positionCaseInsensitive(query,  'select') = 1))\nORDER BY event_time DESC\nLIMIT 100",
     "round": "0s",
     "table": "query_log"
    },
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font><br />    event_time,<br />    user,<br />    query_duration_ms duration,<br />    memory_usage memory,<br />    if(exception<font color=\"yellow\">!=</font><font color=\"lightgreen\">''</font>, <font color=\"lightgreen\">'fail'</font>, <font color=\"lightgreen\">'success'</font>) result,<br />    <font color=\"navajowhite\">concat</font>(<font color=\"navajowhite\">substring</font>(query,<font color=\"cornflowerblue\">1</font>,<font color=\"cornflowerblue\">120</font>), <font color=\"lightgreen\">'...'</font>) query<br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br /><font color=\"darkorange\">WHERE</font> <font color=\"darkcyan\">$timeFilter</font><br />    <font color=\"yellow\">AND</font> <font color=\"darkorange\">type</font> <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$type</font>)<br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br />    <font color=\"yellow\">and</font>(<font color=\"lightgreen\">'$query_type'</font> <font color=\"yellow\">=</font> <font color=\"lightgreen\">'all'</font> <font color=\"yellow\">or</font>(positionCaseInsensitive(query,  <font color=\"lightgreen\">'$query_type'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font>))<br /><font color=\"darkorange\">ORDER BY</font> event_time <font color=\"darkorange\">DESC</font><br /><font color=\"darkorange\">LIMIT</font> <font color=\"cornflowerblue\">1000</font>",
     "query": "SELECT\n    event_time,\n    user,\n    query_duration_ms duration,\n    memory_usage memory,\n    if(exception!='', 'fail', 'success') result,\n    query\nFROM system.query_log\nWHERE $timeFilter\n    AND type in (1,2,3,4)\n    and initial_user ='aiops'\n    and((positionCaseInsensitive(query,  'insert into') = 1) or (positionCaseInsensitive(query,  'select') = 1))\nORDER BY event_time DESC\nLIMIT 100",
     "rawQuery": "SELECT\n    event_time,\n    user,\n    query_duration_ms duration,\n    memory_usage memory,\n    if(exception!='', 'fail', 'success') result,\n    query\nFROM system.query_log\nWHERE event_date >= toDate(1665049851) AND event_date <= toDate(1665053451) AND event_time >= toDateTime(1665049851) AND event_time <= toDateTime(1665053451)\n    AND type in (1,2,3,4)\n    and initial_user ='aiops'\n    and((positionCaseInsensitive(query,  'insert into') = 1) or (positionCaseInsensitive(query,  'select') = 1))\nORDER BY event_time DESC\nLIMIT 100",
     "round": "0s",
     "table": "query_log"
    },
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font><br />    event_time,<br />    user,<br />    query_duration_ms duration,<br />    memory_usage memory,<br />    if(exception<font color=\"yellow\">!=</font><font color=\"lightgreen\">''</font>, <font color=\"lightgreen\">'fail'</font>, <font color=\"lightgreen\">'success'</font>) result,<br />    <font color=\"navajowhite\">concat</font>(<font color=\"navajowhite\">substring</font>(query,<font color=\"cornflowerblue\">1</font>,<font color=\"cornflowerblue\">120</font>), <font color=\"lightgreen\">'...'</font>) query<br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br /><font color=\"darkorange\">WHERE</font> <font color=\"darkcyan\">$timeFilter</font><br />    <font color=\"yellow\">AND</font> <font color=\"darkorange\">type</font> <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$type</font>)<br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br />    <font color=\"yellow\">and</font>(<font color=\"lightgreen\">'$query_type'</font> <font color=\"yellow\">=</font> <font color=\"lightgreen\">'all'</font> <font color=\"yellow\">or</font>(positionCaseInsensitive(query,  <font color=\"lightgreen\">'$query_type'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font>))<br /><font color=\"darkorange\">ORDER BY</font> event_time <font color=\"darkorange\">DESC</font><br /><font color=\"darkorange\">LIMIT</font> <font color=\"cornflowerblue\">1000</font>",
     "query": "SELECT\n    event_time,\n    user,\n    query_duration_ms duration,\n    memory_usage memory,\n    if(exception!='', 'fail', 'success') result,\n    query\nFROM system.query_log\nWHERE $timeFilter\n    AND type in (1,2,3,4)\n    and initial_user ='aiops'\n    and((positionCaseInsensitive(query,  'insert into') = 1) or (positionCaseInsensitive(query,  'select') = 1))\nORDER BY event_time DESC\nLIMIT 100",
     "rawQuery": "SELECT\n    event_time,\n    user,\n    query_duration_ms duration,\n    memory_usage memory,\n    if(exception!='', 'fail', 'success') result,\n    query\nFROM system.query_log\nWHERE event_date >= toDate(1665049851) AND event_date <= toDate(1665053451) AND event_time >= toDateTime(1665049851) AND event_time <= toDateTime(1665053451)\n    AND type in (1,2,3,4)\n    and initial_user ='aiops'\n    and((positionCaseInsensitive(query,  'insert into') = 1) or (positionCaseInsensitive(query,  'select') = 1))\nORDER BY event_time DESC\nLIMIT 100",
     "round": "0s",
     "table": "query_log"
    },
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font><br />    event_time,<br />    user,<br />    query_duration_ms duration,<br />    memory_usage memory,<br />    if(exception<font color=\"yellow\">!=</font><font color=\"lightgreen\">''</font>, <font color=\"lightgreen\">'fail'</font>, <font color=\"lightgreen\">'success'</font>) result,<br />    <font color=\"navajowhite\">concat</font>(<font color=\"navajowhite\">substring</font>(query,<font color=\"cornflowerblue\">1</font>,<font color=\"cornflowerblue\">120</font>), <font color=\"lightgreen\">'...'</font>) query<br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br /><font color=\"darkorange\">WHERE</font> <font color=\"darkcyan\">$timeFilter</font><br />    <font color=\"yellow\">AND</font> <font color=\"darkorange\">type</font> <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$type</font>)<br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br />    <font color=\"yellow\">and</font>(<font color=\"lightgreen\">'$query_type'</font> <font color=\"yellow\">=</font> <font color=\"lightgreen\">'all'</font> <font color=\"yellow\">or</font>(positionCaseInsensitive(query,  <font color=\"lightgreen\">'$query_type'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font>))<br /><font color=\"darkorange\">ORDER BY</font> event_time <font color=\"darkorange\">DESC</font><br /><font color=\"darkorange\">LIMIT</font> <font color=\"cornflowerblue\">1000</font>",
     "query": "SELECT\n    event_time,\n    user,\n    query_duration_ms duration,\n    memory_usage memory,\n    if(exception!='', 'fail', 'success') result,\n    query\nFROM system.query_log\nWHERE $timeFilter\n    AND type in (1,2,3,4)\n    and initial_user ='aiops'\n    and((positionCaseInsensitive(query,  'insert into') = 1) or (positionCaseInsensitive(query,  'select') = 1))\nORDER BY event_time DESC\nLIMIT 100",
     "rawQuery": "SELECT\n    event_time,\n    user,\n    query_duration_ms duration,\n    memory_usage memory,\n    if(exception!='', 'fail', 'success') result,\n    query\nFROM system.query_log\nWHERE event_date >= toDate(1665049851) AND event_date <= toDate(1665053451) AND event_time >= toDateTime(1665049851) AND event_time <= toDateTime(1665053451)\n    AND type in (1,2,3,4)\n    and initial_user ='aiops'\n    and((positionCaseInsensitive(query,  'insert into') = 1) or (positionCaseInsensitive(query,  'select') = 1))\nORDER BY event_time DESC\nLIMIT 100",
     "round": "0s",
     "table": "query_log"
    }
   ]
  },
  { "title": "ZK集群监控", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "资源总览",
   "type": "table-old",
   "description": "分区使用率、磁盘读取、磁盘写入、下载带宽、上传带宽，如果有多个网卡或者多个分区，是采集的使用率最高的网卡或者分区的数值。\n\nTCP_连接数：当前状态为 ESTABLISHED 或 CLOSE-WAIT 的 TCP 连接数\n\nTCP_TW：当前状态为TIME-WAIT的TCP连接数，即等待关闭的TCP连接数",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "node_uname_info{job=\"zk_cluster_exporter\"} - 0",
     "legendFormat": "主机名"
    },
    {
     "expr": "sum(time() - node_boot_time_seconds{job=\"zk_cluster_exporter\"})by(instance)",
     "legendFormat": "运行时间"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=\"zk_cluster_exporter\"} - 0",
     "legendFormat": "总内存"
    },
    {
     "expr": "count(node_cpu_seconds_total{job=\"zk_cluster_exporter\",mode='system'}) by (instance)",
     "legendFormat": "总核数"
    },
    {
     "expr": "node_load5{job=\"zk_cluster_exporter\"}",
     "legendFormat": "5分钟负载"
    },
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{job=\"zk_cluster_exporter\",mode=\"idle\"}[$__interval])) by (instance)) * 100",
     "legendFormat": "CPU使用率"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{job=\"zk_cluster_exporter\"} / (node_memory_MemTotal_bytes{job=\"zk_cluster_exporter\"})))* 100",
     "legendFormat": "内存使用率"
    },
    {
     "expr": "max((node_filesystem_size_bytes{job=\"zk_cluster_exporter\",fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{job=\"zk_cluster_exporter\",fstype=~\"ext.?|xfs\"}) *100/(node_filesystem_avail_bytes {job=\"zk_cluster_exporter\",fstype=~\"ext.?|xfs\"}+(node_filesystem_size_bytes{job=\"zk_cluster_exporter\",fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{job=\"zk_cluster_exporter\",fstype=~\"ext.?|xfs\"})))by(instance)",
     "legendFormat": "分区使用率"
    },
    {
     "expr": "max(rate(node_disk_read_bytes_total{job=\"zk_cluster_exporter\"}[$__interval])) by (instance)",
     "legendFormat": "最大读取"
    },
    {
     "expr": "max(rate(node_disk_written_bytes_total{job=\"zk_cluster_exporter\"}[$__interval])) by (instance)",
     "legendFormat": "最大写入"
    },
    {
     "expr": "node_netstat_Tcp_CurrEstab{job=\"zk_cluster_exporter\"} - 0",
     "legendFormat": "连接数"
    },
    {
     "expr": "node_sockstat_TCP_tw{job=\"zk_cluster_exporter\"} - 0",
     "legendFormat": "TIME_WAIT"
    },
    {
     "expr": "max(rate(node_network_receive_bytes_total{job=\"zk_cluster_exporter\"}[$__interval])*8) by (instance)",
     "legendFormat": "下载带宽"
    },
    {
     "expr": "max(rate(node_network_transmit_bytes_total{job=\"zk_cluster_exporter\"}[$__interval])*8) by (instance)",
     "legendFormat": "上传带宽"
    }
   ]
  },
  {
   "title": "CPU使用率",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{job=\"zk_cluster_exporter\",mode=\"idle\"}[$__interval])) by (instance))*100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Mem使用率",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 69 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{job=\"zk_cluster_exporter\"} - node_memory_MemAvailable_bytes{job=\"zk_cluster_exporter\"}) / node_memory_MemTotal_bytes{job=\"zk_cluster_exporter\"} * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "磁盘每秒读写速率",
   "type": "graph",
   "description": "Reads completed: 每个磁盘分区每秒读完成次数\n\nWrites completed: 每个磁盘分区每秒写完成次数",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "iops", "label": "读取（-）/写入（+）" }
   ],
   "targets": [
    {
     "expr": "avg(rate(node_disk_reads_completed_total{job=\"zk_cluster_exporter\"}[$__interval])) by (instance)",
     "legendFormat": "{{instance}}_读取"
    },
    {
     "expr": "avg(rate(node_disk_writes_completed_total{job=\"zk_cluster_exporter\"}[$__interval])) by (instance)",
     "legendFormat": "{{instance}}_写入"
    }
   ]
  },
  {
   "title": "磁盘每秒读写容量",
   "type": "graph",
   "description": "Read bytes 每个磁盘分区每秒读取的比特数\n\nWritten bytes 每个磁盘分区每秒写入的比特数",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 75 },
   "yaxes": [
    { "format": "Bps", "label": "读取（-）/写入（+）" }
   ],
   "targets": [
    {
     "expr": "avg(rate(node_disk_read_bytes_total{job=\"zk_cluster_exporter\"}[$__interval])) by (instance)",
     "legendFormat": "{{instance}}_读取"
    },
    {
     "expr": "avg(rate(node_disk_written_bytes_total{job=\"zk_cluster_exporter\"}[$__interval])) by (instance)",
     "legendFormat": "{{instance}}_写入"
    }
   ]
  },
  {
   "title": "磁盘每次IO读写耗时",
   "type": "graph",
   "description": "IO time seconds 每个磁盘分区输入/输出操作花费的秒数",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 75 },
   "yaxes": [
    { "format": "s", "label": "读取（-）/写入（+）" }
   ],
   "targets": [
    {
     "expr": "avg(rate(node_disk_read_time_seconds_total{job=\"zk_cluster_exporter\"}[$__interval]) / rate(node_disk_reads_completed_total{job=\"zk_cluster_exporter\"}[$__interval])) by (instance)",
     "legendFormat": "{{instance}}_读取"
    },
    {
     "expr": "avg(rate(node_disk_write_time_seconds_total{job=\"zk_cluster_exporter\"}[$__interval]) / rate(node_disk_writes_completed_total{job=\"zk_cluster_exporter\"}[$__interval])) by (instance)",
     "legendFormat": "{{instance}}_写入"
    }
   ]
  },
  {
   "title": "avg_latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "avg_latency", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "znode_count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "znode_count", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "ephemerals_count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 89 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ephemerals_count", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "global_sessions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "global_sessions", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "outstanding_requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 96 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "outstanding_requests", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "connection_dropped_count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 102 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "connection_drop_count", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "connection_rejected_count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 102 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "connection_rejected", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "packets_sent",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 108 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "packets_sent", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "packets_received",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 108 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "packets_received", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}